// front_end/src/app/components/charts/multi-dim/multi-dim.component.ts
import { Component, OnInit, ElementRef, ViewChild } from '@angular/core';

// Service
import {MainEventService} from '../../../core/services/main.event.service';

import { MainEvent } from '../../../data/client-enums';
import { ExperimentDescription } from '../../../data/experimentDescription.model';
import { Solution } from '../../../data/taskData.model';

interface PointExp {[Key: string]: any}

@Component({
  selector: 'multi-dim',
  templateUrl: './multi-dim.component.html',
  styleUrls: ['./multi-dim.component.scss']
})
export class MultiDimComponent implements OnInit {

  // Experiment configurations
  experimentDescription: ExperimentDescription
  searchspace: object
  resultParamsRange: any // Map. results parameters with possible ranges
  parameter_names: any
  keyParam: any
  rootParam: any
  currentDiagram: any
  experiment: any

  // Best point
  allPoints = new Set<PointExp>()
  // Default point
  defaultPoint: PointExp

  // Proposed solution from model
  solution: Solution

  resetRes() {
    this.experimentDescription = undefined
    this.defaultPoint = undefined
    this.allPoints.clear()
    this.solution = undefined
  }


  constructor(
    private ioMain: MainEventService,
  ) { }

  ngOnInit() {
    this.initMainEvents();
  }

  isModelType(type: String) {
    // used in HTML template
    return this.experimentDescription && this.experimentDescription.Predictor.models[0].Type == type
  }

  // --------------------------   Main-node
  private initMainEvents(): void {

    //                            Main events
    this.ioMain.onEvent(MainEvent.EXPERIMENT)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'description') {
          let obj = JSON.parse(message.body)
          this.resetRes()
          this.experimentDescription = obj['experiment_description']
          this.searchspace = obj['searchspace_description']
          this.rootParam = this.searchspace["root_parameters_list"]
          this.experiment = this.searchspace["name"]
          let priorities = this.experimentDescription["TaskConfiguration"]["ObjectivesPriorities"]
          let i = priorities.indexOf(Math.max(...priorities));
          this.keyParam = this.experimentDescription["TaskConfiguration"]["Objectives"][i]
        }

      });

    this.ioMain.onEvent(MainEvent.DEFAULT) // Default configuration
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          let configs = JSON.parse(message.body)
          configs.forEach(configuration => {
            if (configuration) {
              this.chose(configuration)
              this.defaultPoint = configuration // In case if only one point default
              var alphas = new Array();;
              this.parameter_names.forEach(key => {
                alphas.push(configuration.configurations[key])
              })
              let point = this.zip(this.parameter_names, alphas)
              point.set('result', configuration.results[this.keyParam])
              this.allPoints.add(point)
              this.render()
            } else {
              console.log("Empty default")
            }
          })
          console.log('Default:', configs)
        }
      });

    this.ioMain.onEvent(MainEvent.NEW) // New task results
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          let configs = JSON.parse(message.body)
          configs.forEach(configuration => {
        if (configuration) {
            this.chose(configuration)
            var alphas = new Array();;
            this.parameter_names.forEach(key => {
              alphas.push(configuration.configurations[key])
            })
            let point = this.zip(this.parameter_names, alphas)
            point.set('result', configuration.results[this.keyParam])
            this.allPoints.add(point)
            this.render()
          }
          else {
            console.log("Empty task")
          }
          })
        }
      });
    this.ioMain.onEvent(MainEvent.FINAL) // The final configuration, suggested by BRISE.
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          let configs = JSON.parse(message.body)
          configs.forEach(configuration => {
            if (configuration) {
              this.solution = configuration // In case if only one point solution
              console.log('Final:', configs)
            } else {
              console.log("Empty solution")
            }
          })
        }
      });
  }

  render(){
    const element = document.getElementById(this.currentDiagram)
    var trace = [{
      type: 'parcoords',
      line: {
        showscale: true,
        // reversescale: true,
        colorscale: 'Jet',
        color: this.unpack(this.allPoints, 'result')
      },
      dimensions: this.dimmensionsData()
    }];

    var layout = {
      title: {
        text: this.currentDiagram,
        font: {
          size: 20
        },
        xref: 'paper',
        x: 0.05,
      }
    }

    Plotly.react(element, trace, layout)
  }

  dimmensionsData() {
    let data = [] // accommodate dimensional obj
    this.resultParamsRange.size && this.resultParamsRange.forEach((range: Array<any>, param: String)=>{
      if (param != this.experiment){
        let dim = this.factoryDimension(param, range) // make dimensional object through all results by one parameter
        data.push(dim) // add new dimension object for plotting
      }
    })
    return data
  }
  factoryDimension(parameter: String, valuesRange: Array<any> = null) {
    let dimValues = this.unpack(this.allPoints, parameter)
    let dim: any = {
      values: dimValues,
      label: parameter.replace(/_/g, " ")
    }
    // If values are not numerical.
    if (valuesRange && (typeof valuesRange[0] == "string" || typeof valuesRange[0] == "boolean")) {
      dim.tickvals = Array.from(Array(valuesRange.length).keys())
      dim.ticktext = valuesRange
      dim.values = dimValues.map(value => dim.tickvals[dim.ticktext.indexOf(value)])
    }
    return dim
  }
  // Returns an array of values by key from all dictionaries
  unpack(set, key) {
    let selection = []
    set.forEach(point=>{  // point is key value store - Map
      selection.push(point.get(key));
    });
    return selection
  }
  // merge key and values arrays in key
  zip(keys:Array<any>, values:Array<any>) {
    let result = new Map()
    if (keys.length == values.length) {
      keys.forEach((key, i) => result.set(key, values[i]))
    }
    return result
  }
  chose(configuration){
    this.currentDiagram = configuration.configurations[this.experiment]
    let index = this.rootParam.indexOf(this.currentDiagram)
    this.parameter_names = Object.keys(this.searchspace["boundaries"][index]["Boundaries"])
    let rangeValues = Object.values(this.searchspace["boundaries"][index]["Boundaries"])
    this.resultParamsRange = this.zip(this.parameter_names, rangeValues)
    this.resultParamsRange.set('result', undefined) // range for results is undefined
  }
}

<li *ngFor="let item of rootParam">
  <mat-card *ngIf="isModelType('brise.TreeParzenEstimator')">
    <div id={{item}}></div>
  </mat-card>
</li>

// frontend/src/widgets/charts/multi-dim/ui/MultiDim.vue
<script setup lang="ts">
import { ref, onMounted, watch, onUnmounted } from 'vue'
import { storeToRefs } from 'pinia'

// constant
import { MainEvent, useMainEventStore } from '../../../../entities/main'
// import type { Solution } from '../../../../entities/task/model/task-data.model'

import { cleanIdentifier } from '../../../../shared/lib'

import { zip, unpack, dimmensionsData } from '../lib/dimension-lib'

// initialize store
const store = useMainEventStore()
const { experiment_description, searchspace } = storeToRefs(store)


const parameter_names = ref<string[]>()
const currentDiagram = ref<string>()
let experiment: string = ''
const rootParam = ref<any[]>([])
let resultParamsRange = ref<Map<string, any>>()
let keyParam = ref('')

// collect all points
const allPoints = ref<Map<string, any>[]>([])
// let defaultPoint: any
// let solution: Solution | null = null

let renderTimer: ReturnType<typeof setTimeout> | null = null

function resetRes() {
    allPoints.value = []
    // solution = null
    // defaultPoint = null
}



async function chose() {
    if (!rootParam.value || rootParam.value.length === 0) return

    let index = rootParam.value.indexOf(experiment)
    if (index === -1) {
        index = rootParam.value.findIndex(p => cleanIdentifier(p) === experiment)
    }
    if (index === -1) index = 0 // fallback

    currentDiagram.value = rootParam.value[index]

    const boundariesObj = searchspace.value["boundaries"]?.[index]?.["Boundaries"]
    if (!boundariesObj) return

    parameter_names.value = Object.keys(boundariesObj)
    let rangeValues = Object.values(boundariesObj)
    const shortNames = parameter_names.value.map(cleanIdentifier)

    resultParamsRange.value = zip(shortNames, rangeValues)
    resultParamsRange.value.set('result', undefined)
}
function initMainEvents() {
    watch([experiment_description, searchspace], () => {
        if (!experiment_description.value || !searchspace.value) {
            return
        }
        resetRes()

        rootParam.value = searchspace.value["root_parameters_list"]
        experiment = searchspace.value["name"]

        chose()
        let priorities = experiment_description.value?.Context?.TaskConfiguration?.Objectives

        if (priorities) {
            keyParam.value = Object.keys(priorities)[0]
        }
    },
        {
            deep: true,
            immediate: true
        })

    // Default message
    store.onEvent(MainEvent.DEFAULT)?.subscribe(async (message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            if (!rootParam.value || !experiment) {
                console.warn('not ready yet - rootParam or experiment not there ')
                return
            }
            let configs = JSON.parse(message.body)
            let count = 0;
            for (const configuration of configs) {
                if (configuration) {
                    if (!parameter_names.value) return
                    // defaultPoint = configuration
                    let alphas = new Array();
                    parameter_names.value.forEach((key: any) => {
                        const rawVal = configuration.configurations[key]
                        // cleaning the labels 
                        alphas.push(cleanIdentifier(rawVal))
                    })
                    let point = zip(parameter_names.value.map(cleanIdentifier), alphas)
                    point.set('result', configuration.results[keyParam.value])
                    allPoints.value.push(point)
                }

                count++;
                if (count % 50 === 0 && typeof scheduler !== 'undefined' && scheduler.yield) {
                    await scheduler.yield();
                }
            }

            if (renderTimer) clearTimeout(renderTimer)
            renderTimer = setTimeout(async () => {
                if (typeof scheduler !== 'undefined' && scheduler.yield) {
                    await scheduler.yield()
                }
                render()
                renderTimer = null
            }, 500)
        }
    });

    // New points
    store.onEvent(MainEvent.NEW)?.subscribe(async (message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            if (!rootParam.value || !rootParam.value.length || !experiment) {
                return
            }
            let configs = JSON.parse(message.body)
            let count = 0;

            for (const configuration of configs) {
                if (configuration) {
                    if (!parameter_names.value) return
                    var alphas = new Array();
                    parameter_names.value.forEach((key: any) => {
                        const rawVal = configuration.configurations[key]
                        alphas.push(cleanIdentifier(rawVal))
                    })
                    let point = zip(parameter_names.value.map(cleanIdentifier), alphas)
                    point.set('result', configuration.results[keyParam.value])
                    allPoints.value.push(point)
                }

                count++;
                if (count % 50 === 0 && typeof scheduler !== 'undefined' && scheduler.yield) {
                    await scheduler.yield();
                }
            }

            if (renderTimer) clearTimeout(renderTimer)
            renderTimer = setTimeout(async () => {
                if (typeof scheduler !== 'undefined' && scheduler.yield) {
                    await scheduler.yield()
                }
                render()
                renderTimer = null
            }, 500)
        }
    });

    // Final message
    store.onEvent(MainEvent.FINAL)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            if (!parameter_names.value) return
            // let configs = JSON.parse(message.body)
            // configs.forEach((configuration: any) => {
            //     if (configuration) {
            //         solution = configuration
            //     }
            // });
        }
    })
}
async function render(): Promise<void> {
    if (!currentDiagram.value) return

    const Plotly = store.plotlyInstance
    const element = document.getElementById(currentDiagram.value)

    if (!Plotly || !element) {
        return
    }

    const dims = dimmensionsData(resultParamsRange.value, experiment, allPoints.value)
    if (!dims || dims.length === 0) return

    var trace = [{
        type: 'parcoords' as const,
        line: {
            showscale: true,
            colorscale: 'Jet',
            color: unpack(allPoints.value, 'result').map((v: any) => Number(v) || 0)
        },
        dimensions: dims
    }];

    var layout = {
        margin: { l: 200, r: 50, b: 50, t: 50 },
        title: {
            text: cleanIdentifier(currentDiagram.value),
            font: { size: 18 }
        }
    }

    Plotly.react(element, trace, layout)
}



onMounted(() => {
    initMainEvents()
})

onUnmounted(() => {
    if (renderTimer) clearTimeout(renderTimer)
    const element = document.getElementById(currentDiagram.value!)
    const Plotly = store.plotlyInstance

    if (element && Plotly) {
        Plotly.purge(element)
    }
})
</script>

<template>
  <div
    v-for="item in rootParam"
    :key="item"
  >
    <div
      :id="item"
      style="width:100%; height:500px;"
    />
  </div>
</template>
