// frontend-new/src/widgets/task-list/ui/TaskList.vue
<script setup lang="ts">
import { onMounted, ref, computed, watch } from 'vue'
import { storeToRefs } from 'pinia'

import { MainEvent } from '../../../entities/main'
import { Task } from '../../../entities/task/model/task-data.model';
//service
import { useMainEventStore } from '../../../entities/main'


const result = ref<Task[]>([])

const update = ref(false)

// task object for expanding a row in a table
const focus = ref<Task | null>(null)

// initialize store
const store = useMainEventStore()
// destructure reactive value from main.event.store
const { experiment_description, searchspace } = storeToRefs(store)
function refresh() {
    result.value = []

    update.value = true
}
function clearFocus(): void {
    focus.value = null
}

const filterValue = ref('')

function applyFilter(value: string) {
    filterValue.value = value.trim().toLocaleLowerCase()
}

const filteredResult = computed(() => {
    if (!filterValue.value) return result.value

    let params = ''
    let results = ''
    return result.value.filter(task => {
        Object.values(task.config).forEach((param: any) => {
            params = params + param
        })

        Object.values(task.meta.result).forEach(result => {
            results = results + String(result)

        });
        const dataStr = task.id +
            params +
            results;
        return dataStr.indexOf(filterValue.value) != -1;
    })

})

// alternative for function sortingDataAccessor() in vue (rendering through data-table)

const headers = [
    { title: 'Task ID', key: 'id' },
    {
        title: 'Configuration',
        key: 'run',
        sortRaw: (a: Task, b: Task) => {
            const valA = Object.values(a.config)[0] as string
            const valB = Object.values(b.config)[0] as string
            return valA < valB ? -1 : 1
        }
    },
    {
        title: 'Result',
        key: 'roundedResults',
        sortRaw: (a: Task, b: Task) => {
            const valA = Number(Object.values(a.meta.result)[0])
            const valB = Number(Object.values(b.meta.result)[0])
            return valA - valB
        }
    }
]



function searchTasks(search: Record<string, any>) {
    let search_without_Nones = replaceNones(search && Object.values(search))
    let select: Array<Task> = []
    if (arguments.length && result.value.length) {
        result.value.map(task => {
            let paramsValues = replaceNones(task.config && Object.values(task.config))
            let count_diff = 0
            for (let i = 0; i < search_without_Nones.length; ++i) {
                if (search_without_Nones[i] != paramsValues[i]) {
                    count_diff = count_diff + 1
                }
            }
            if (count_diff == 0) {
                select.push(task)
            }
        })
    }
    return select
}

function replaceNones(config: Record<string, any>) {
    let res_config = new Array<any>()
    Array.prototype.forEach.call(config, param => {
        if (param == '' || param == null) {
            res_config.push('None')
        }
        else {
            res_config.push(param)
        }
    });
    return res_config
}

function getAverageResult(search: Record<string, any>) {
    let select = searchTasks(search)
    let avg_res: any[] = new Array<any>()
    let sum = new Array<Array<any>>()
    for (let i = 0; i < Object.values(select[0].meta.result).length; i++) {
        sum[i] = new Array<any>();
    }
    select && select.map(task => {
        for (let i = 0; i < Object.values(task.meta.result).length; i++) {
            task.meta && sum[i].push(Number(Object.values(task.meta.result)[i]))
        }
    })
    for (let i = 0; i < Object.values(select[0].meta.result).length; i++) {
        avg_res[i] = sum[i].reduce((a, b) => a + b, 0) / sum[i].length
    }
    return avg_res
}

function initMainEvents(): void {
    store.onEvent(MainEvent.NEW)?.subscribe((message) => {
        if (message.headers['message_subtype'] === 'task') {
            var fresh: Task = new Task(JSON.parse(message.body))
            var params_array = Object.values(fresh.config)
            fresh.stub_config = replaceNones(params_array)
            // add a new task if it is not in the this.result
            !result.value.includes(fresh, -1) && result.value.push(fresh);
            console.log('new', message)
            console.log('message raw', message.body)
            console.log('fresh task', fresh)
            console.log('fresh meta', fresh.meta)
        }
    });

    watch(experiment_description, () => {
        update.value = false
        refresh()
    },
        // reactive object from store, need deep to tracl properties of the object
        { deep: true })

}

onMounted(() => {
    initMainEvents()
})

const expanded = ref([])
</script>

<template>
    <div class="box" v-if="update">
        <v-card elevation="4">
            <v-card-title>
                <h5>Result <span class="length">({{ result.length }})</span></h5>
            </v-card-title>
            <v-text-field variant="outlined" @keyup="(e: any) => applyFilter(e.target.value)" placeholder="Filter">
            </v-text-field>

            <v-data-table show-expand v-model:expanded="expanded" class="result" :headers="headers"
                :items="filteredResult">
                <!-- Configuration Column -->
                <template v-slot:item.run="{ item }">
                    <span v-for="(value, key) in item.config" :key="key">
                        {{ key }} = {{ value }} ;
                    </span>
                </template>
                <template v-slot:item.roundedResults="{ item }">
                    <span v-for="(value, key) in item.roundedResults" :key="key">
                        {{ key }} = {{ value }} ;
                    </span>
                </template>


                <!-- Expanded Content Column -->
                <template #expanded-row="{ item }">

                    <v-chip v-for="(value, key) in item.config" :key="key">
                        {{ key }}: {{ value }}
                    </v-chip>


                    <v-list>
                        <v-list-item>Worker: {{ item.meta.worker }}</v-list-item>
                        <v-list-item>Repetitions {{ searchTasks(item.config).length }}</v-list-item>
                        <v-list-item>
                            Average result:
                            <span v-for="(res, index) in getAverageResult(item.config)" :key="index">
                                {{ res.toFixed(2) }}
                                <span v-if="index < getAverageResult(item.config).length - 1"> ; </span>
                            </span>
                        </v-list-item>
                    </v-list>
                </template>
            </v-data-table>
        </v-card>
    </div>
</template>

// front-end/src/app/components/task-list/task-list.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';

import { MatPaginator, MatTable, MatSort, MatTableDataSource } from '@angular/material';
import { animate, state, style, transition, trigger } from '@angular/animations';

// Service
import {MainEventService} from '../../core/services/main.event.service';


import { Task } from '../../data/taskData.model';

import { MainEvent } from '../../data/client-enums';

import { ExperimentDescription } from '../../data/experimentDescription.model';


@Component({
  selector: 'app-task-list',
  templateUrl: './task-list.component.html',
  styleUrls: ['./task-list.component.scss'],
  animations: [
    trigger('detailExpand', [
      state('collapsed', style({ height: '0px', minHeight: '0', display: 'none' })),
      state('expanded', style({ height: '*' })),
      transition('expanded <=> collapsed', animate('225ms cubic-bezier(0.4, 0.0, 0.2, 1)')),
    ]),
  ],
})
export class TaskListComponent implements OnInit {

  @ViewChild('table') table: MatTable<Element>;
  @ViewChild(MatPaginator) paginator: MatPaginator;
  @ViewChild(MatSort) sort: MatSort;

  stack: Array<any> = []
  result: Array<Task> = []

  focus: any
  displayedColumns: String[] =  ['id', 'run', 'result'];
  experimentDescription: ExperimentDescription
  searchSpaceDescription: Object
  update: boolean

  public resultData: MatTableDataSource<Task>

  constructor(private ioMain: MainEventService) {
    this.resultData = new MatTableDataSource(this.result);

    this.resultData.filterPredicate = (task, filter) => {
      let params: String
      let results: String
      task.run.param.forEach(param => {
        params = params + param
      });
      Object.values(task.meta.result).forEach(result => {
        results = results + String(result)
      });
      const dataStr = task.id +
        params +
        results;
      return dataStr.indexOf(filter) != -1;
    }
  }

  ngOnInit() {
    this.resultData.paginator = this.paginator;
    this.resultData.sort = this.sort;
    this.resultData.sortingDataAccessor = this.sortingDataAccessor;
    this.initMainEvents()

  }

  refresh() {
    this.result = []
    this.resultData = new MatTableDataSource([])
    this.update = true
  }
  clearFocus():void {
    this.focus = null
  }

  applyFilter(filterValue: string) {
    this.resultData.filter = filterValue.trim().toLowerCase();

    if (this.resultData.paginator) {
      this.resultData.paginator.firstPage();
    }
  }

  sortingDataAccessor(data, sortHeaderId) {
    switch (sortHeaderId) {
      case 'id': return data.id ? data.id : null;
      case 'run': return Object.values(data.run.param)[0] ? Object.values(data.run.param)[0] : null;
      case 'result': return Object.values(data.meta.res_config)[0] ? Number(Object.values(data.meta.res_config)[0]) : null;
      default: return data[sortHeaderId];
    }
  }

  searchTasks(search: Array<any>) {
    let search_without_Nones = this.replaceNones(search)
    let select: Array<Task> = []
    if (arguments.length && this.result.length) {
      this.result.map(task => {
        let paramsValues = this.replaceNones(task.config && Object.values(task.config))
        let count_diff = 0
        for (let i = 0; i < search_without_Nones.length; ++i){
          if (search_without_Nones[i] != paramsValues[i]){
            count_diff = count_diff + 1
          }
        }
        if(count_diff == 0){
          select.push(task)
        }
      })
    }
    return select
  }

  replaceNones(config: Array<any>){
    let res_config = new Array<any>()
    config.forEach(param => {
      if(param == '' || param == null){
        res_config.push('None')
      }
      else{
        res_config.push(param)
      }
    });
    return res_config
  }

  getAverageResult(search: Array<any>) {
    let select = this.searchTasks(search)
    let avg_res:any[] = new Array<any>()
    let sum = new Array<Array<any>>()
    for (let i = 0; i < Object.values(select[0].meta.result).length; i++) {
      sum[i]  = new Array<any>();
    }
    select && select.map(task => {
      for (let i = 0; i < Object.values(task.meta.result).length; i++) {
        task.meta && sum[i].push(Number(Object.values(task.meta.result)[i]))
      }
    })
    for (let i = 0; i < Object.values(select[0].meta.result).length; i++) {
      avg_res[i] = sum[i].reduce((a, b) => a + b, 0)/sum[i].length
    }
    return avg_res
  }

  // --------------------- MainEvents ---------------
  private initMainEvents(): void {
    this.ioMain.onEvent(MainEvent.EXPERIMENT)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'description') {
          this.experimentDescription = JSON.parse(message.body)['experiment_description'];
          this.searchSpaceDescription = JSON.parse(message.body)['searchspace_description'];
          this.update = false
          this.refresh()
        }
      });

    this.ioMain.onEvent(MainEvent.NEW)
      .subscribe((message) => {
        if (message.headers['message_subtype'] === 'task') {
          var fresh: Task = new Task(JSON.parse(message.body))
          var params_array = String(fresh.config).split(',')
          fresh.stub_config = this.replaceNones(params_array)
          // add a new task if it is not in the this.result
          !this.result.includes(fresh, -1) && this.result.push(fresh);
          this.resultData.data = this.result;
        }
      });
  }
}

<!-- <div class="box"  *ngIf="isModelType('regression')"> -->
<div class="box" *ngIf="isModelType('regression')">

  <!-- <mat-card class="focus" *ngIf=focus>
    <!- FOCUS task. select from lists ->
  
    <button mat-icon-button (click)="clearFocus()" class="focus-clear">
      <mat-icon>close</mat-icon>
    </button>
  
    <mat-card-title color="primary">ID: {{focus.id.substr(0, 5)}}</mat-card-title>
    <mat-tab-group>
      <mat-tab label="Result">
        <mat-list role="list">
          <mat-list-item role="listitem">
            <mat-icon>gradient</mat-icon>
            <span>Method: </span>
            <span> {{focus.run.method}}</span>
          </mat-list-item>
          <mat-list-item role="listitem">
            <mat-icon>whatshot</mat-icon>
            <span>Energy: </span>
            <span> {{focus.meta_data.result.energy}}</span>
          </mat-list-item>
          <mat-list-item role="listitem">
            <mat-icon>memory</mat-icon>
            <span>Frequency: </span>
            <span> {{focus.meta_data.result.frequency}}</span>
          </mat-list-item>
          <mat-list-item role="listitem">
            <mat-icon>layers</mat-icon>
            <span>Threads: </span>
            <span> {{focus.meta_data.result.threads}}</span>
          </mat-list-item>
          <mat-list-item role="listitem">
            <mat-icon>timer</mat-icon>
            <span>Time: </span>
            <span> {{ (focus.meta_data?.result.time > 0) ? (focus.meta_data.result.time | date: 'mm:ss') : ""}}</span>
          </mat-list-item>
        </mat-list>
      </mat-tab>
      <mat-tab label="Meta data">
        <mat-list role="list">
          <mat-list-item role="listitem">
            <mat-icon>rowing</mat-icon>
            <span>Worker:</span>
            <span>{{focus.meta_data.appointment}}</span>
          </mat-list-item>
          <mat-list-item role="listitem">
            <mat-icon>list</mat-icon>
            <span>Accept:</span>
            <span>{{ (focus.meta_data?.accept > 0) ? (focus.meta_data.accept | date: 'mm:ss') : ""}}</span>
          </mat-list-item>
          <mat-list-item role="listitem">
            <mat-icon>directions</mat-icon>
            <span>Receive:</span>
            <span>{{ (focus.meta_data?.receive > 0) ? (focus.meta_data.receive | date: 'mm:ss') : ""}}</span>
          </mat-list-item>
        </mat-list>
      </mat-tab>
    </mat-tab-group>
  </mat-card> -->
  <!-- end focus -->



    <!-- <mat-card class="stack">                                     
      <mat-card-header>
        <h3>Stack <span class="length">({{stack?.length}})</span></h3>
      </mat-card-header> 
      <mat-card-content>
        <mat-list dense role="list" *ngIf=stack>
          <mat-list-item *ngFor="let task of stack" 
            (click)="taskInfo(task.id)" role="listitem" 
            [class.selected]="task.id === this.focus?.id">
            <mat-icon matListIcon>folder</mat-icon>
            <h3 matLine> {{task.id.substr(0, 5)}} </h3>
            <p matLine>
              <span> {{task.run?.param?.frequency}} </span>
              <span class="demo-2"> -- {{task.run?.param?.threads}} </span>
            </p>
            <button mat-icon-button (click)="taskInfo(task.id)">
              <mat-icon>info</mat-icon>
            </button>
          </mat-list-item>
        </mat-list>
      </mat-card-content>
    </mat-card>  -->

    <!-- RESULT table -->
    <mat-card class="result">   
      <mat-card-header>
        <h3>Result <span class="length">({{result?.length}})</span></h3>
      </mat-card-header> 

      <mat-card-content>
        <mat-form-field>
          <input matInput (keyup)="applyFilter($event.target.value)" placeholder="Filter">
        </mat-form-field>
        <div class="mat-elevation-z8" >
          <table mat-table #table [dataSource]="resultData" multiTemplateDataRows matSort>
        
            <!-- Id Column -->
            <ng-container matColumnDef="id">
              <th mat-header-cell *matHeaderCellDef mat-sort-header> ID </th>
              <td mat-cell *matCellDef="let task"> {{task?.id?.toString().substr(0, 5)}} </td>
            </ng-container>
        
            <!-- Congiguration Column -->
            <ng-container matColumnDef="run">
              <th mat-header-cell *matHeaderCellDef mat-sort-header>
                Configuration
              </th>
              <td mat-cell *matCellDef="let task">
                {{task.run?.param?.frequency}} - {{task.run?.param?.threads}}
                <!-- <p>{{task.run?.method}}</p> -->
              </td>
            </ng-container>
        
            <!-- File Column -->
            <ng-container matColumnDef="file">
              <th mat-header-cell *matHeaderCellDef mat-sort-header>
                File
              </th>
              <td mat-cell *matCellDef="let task">
                {{task.config?.ws_file | lowercase}}
              </td>
            </ng-container>
        
            <!-- Result Column -->
            <ng-container matColumnDef="result">
              <th mat-header-cell *matHeaderCellDef mat-sort-header>
                Energy
              </th>
              <td mat-cell *matCellDef="let task">
                {{task.meta?.result?.energy}}
              </td>
            </ng-container>
        
            <!-- Time Column -->
            <ng-container matColumnDef="time">
              <th mat-header-cell *matHeaderCellDef mat-sort-header>
                Time (m:ss:SS)
              </th>
              <td mat-cell *matCellDef="let task">
                {{ (task.meta?.result?.time > 0) ? (task.meta?.result?.time | date: 'mm:ss`SS') : ""}}
              </td>
            </ng-container>

            <!-- Expanded Content Column - 
              The detail row is made up of this one column that spans across all columns -->
            <ng-container matColumnDef="expandedDetail">
              <td mat-cell *matCellDef="let task" [attr.colspan]="displayedColumns.length">
                <div class="example-element-detail" 
                [@detailExpand]="task == focus ? 'expanded' : 'collapsed'" *ngIf="task == focus">
                  <mat-list dense role="list">
                    <mat-list-item role="listitem">
                      <mat-icon>gradient</mat-icon>
                      <span>Method: </span>
                      <span> {{task?.run?.method}}</span>
                    </mat-list-item>
                    <mat-list-item role="listitem">
                      <mat-icon>rowing</mat-icon>
                      <span>Worker:</span>
                      <span>{{task?.meta?.appointment}}</span>
                    </mat-list-item>
                  </mat-list>
                  <mat-list dense role="list">
                    <mat-list-item role="listitem">
                      <mat-icon>list</mat-icon>
                      <span>Accept:</span>
                      <span>{{ (task?.meta?.accept > 0) ? (task.meta?.accept | date: 'EEEE, h:mm:ss`S') : ""}}</span>
                    </mat-list-item>
                    <mat-list-item role="listitem">
                      <mat-icon>directions</mat-icon>
                      <span>Receive:</span>
                      <span>{{ (task?.meta?.receive > 0) ? (task.meta?.receive | date: 'EEEE, h:mm:ss`SS') : ""}}</span>
                    </mat-list-item>
                  </mat-list>
                  <mat-list dense role="list">
                    <mat-list-item role="listitem">
                      <mat-icon>done_all</mat-icon>
                      <span>Reiteration:</span>
                      <span>{{searchTasks([task.run?.param?.frequency, task.run?.param?.threads]).length}}</span>
                    </mat-list-item>
                    <mat-list-item role="listitem">
                      <mat-icon>settings_ethernet</mat-icon>
                      <span>Average energy:</span>
                      <span>{{getAverageResult([task.run?.param?.frequency, task.run?.param?.threads]) | number: '2.1-2'}} </span>
                    </mat-list-item>
                  </mat-list>
                </div>
              </td>
            </ng-container>
        
            <tr mat-header-row *matHeaderRowDef="displayedColumns;"></tr>
            <tr mat-row *matRowDef="let task; columns: displayedColumns;"
              class="example-element-row" 
              [class.example-expanded-row]="focus == task"
              (click)="focus == task ? focus = null : focus = task">
            </tr>
            <tr mat-row *matRowDef="let row; columns: ['expandedDetail']" class="example-detail-row"></tr>
          </table>
          <!--<mat-paginator [pageSizeOptions]="[10, 25, 100]" showFirstLastButtons></mat-paginator>-->
        </div>

      </mat-card-content>
    </mat-card>  <!-- end results -->

</div>
