// front-end/src/app/components/info-board/info-board.component.ts
import { Component, OnInit } from '@angular/core';
// Material
import { MatSnackBar } from '@angular/material';

// Service
import {MainEventService} from '../../core/services/main.event.service';

// Constant
import { MainEvent } from '../../data/client-enums';
import { Solution } from '../../data/taskData.model';

interface NewsPoint  {
  'time': any;
  'message': string;
}

@Component({
  selector: 'info-board',
  templateUrl: './info-board.component.html',
  styleUrls: ['./info-board.component.scss']
})
export class InfoBoardComponent implements OnInit {
  // Steps for expansion. Material.angular
  panelOpenState = false;

  // Information log
  news: Set<NewsPoint> = new Set()

  solution: Solution
  configWithNones: String
  default_configuration: any

  globalConfig: object
  experimentDescription: object
  searchspace: object

  constructor(
    private ioMain: MainEventService,
    public snackBar: MatSnackBar
  ) { }

  ngOnInit() {
    this.initMainEvents()
  }

  refresh(){
    this.solution = undefined
    this.news = new Set()
  }

  private initMainEvents(): void {

    // ----                     Main events
    this.ioMain.onEvent(MainEvent.DEFAULT)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          let obj = JSON.parse(message.body)
          this.default_configuration = obj[0]
          let temp: NewsPoint = {'time': Date.now(), 'message': 'Default configuration results received' }
          this.snackBar.open(temp['message'], '×', {
            duration: 3000
          });
        }
      });

    this.ioMain.onEvent(MainEvent.FINAL)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          let obj = JSON.parse(message.body)
          this.solution = obj[0];
          this.configWithNones = String(this.solution.configurations)
          this.configWithNones = this.configWithNones.replace(",,", ",None,")
          let temp = {
            'time': Date.now(),
            'message': '★★★ The optimum result is found. The best point is reached ★★★'
          }
          this.snackBar.open(temp['message'], '×', {
            duration: 3000
          });
          this.news.add(temp)
        }
      });

    this.ioMain.onEvent(MainEvent.LOG) // For information messages
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'info' || message.headers['message_subtype'] === 'error') {
          let obj = JSON.parse(message.body)
          let temp = {'time': Date.now(), 'message': obj}
          this.snackBar.open(temp['message'], '×', {
            duration: 3000
          });
          this.news.add(temp)
        }
      });

    this.ioMain.onEvent(MainEvent.EXPERIMENT)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'description') {
          let obj = JSON.parse(message.body)
          this.globalConfig = obj['global_configuration']
          this.experimentDescription = obj['experiment_description']
          this.searchspace = obj['searchspace_description']
          this.refresh()
          this.searchspace['size'] = parseFloat(this.searchspace['size'])
          let temp = {
            'time': Date.now(),
            'message': 'The main configurations of the experiment are obtained. Let\'s go! '
          }
          this.snackBar.open(temp['message'], '×', {
            duration: 3000
          });
          this.news.add(temp)
          console.log("Experiment description: ", obj)
          }
      });
    this.ioMain.onEvent(MainEvent.NEW)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          let configs = JSON.parse(message.body)
          configs.forEach(configuration => {
            if (configuration) {
              let temp = {
                'time': Date.now(),
                'message': 'New results for ' + String(configuration['configurations'])
              }
              this.snackBar.open(temp['message'], '×', {
                duration: 3000
              });
              this.news.add(temp)
            } else {
              console.log("Empty configuration")
            }
          })
        }
      });
    this.ioMain.onEvent(MainEvent.PREDICTIONS)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          let obj = JSON.parse(message.body)
          let temp = {
            'time': Date.now(),
            'message': 'Prediction obtained. ' + obj.length + ' predictions'
          }
          this.snackBar.open(temp['message'], '×', {
            duration: 3000
          });
          this.news.add(temp)
        }
      });
  }

}


<mat-accordion>
  <!-- Panel 1 -->
  <mat-expansion-panel [disabled]="!news">
    <mat-expansion-panel-header class="info">
      <mat-panel-title>
        Info messages
      </mat-panel-title>
      <mat-panel-description >
         Basic information from the workflow of experiments ({{news ? news.size : "0"}})
         <mat-icon>
          input
          </mat-icon>
      </mat-panel-description>
    </mat-expansion-panel-header>
    <!-- Logs list  -->
    <ng-template matExpansionPanelContent>
      <mat-list dense role="list" *ngIf=news>
        <mat-list-item role="listitem" *ngFor="let info of news">
          <mat-icon mat-list-icon>done</mat-icon>
          <p mat-line>{{info.message}}</p>
          <mat-divider></mat-divider>
          <p class="time" mat-line> {{info.time | date:'shortTime'}} </p>
        </mat-list-item>
      </mat-list>
    </ng-template>
  </mat-expansion-panel>

  <!-- Panel 2 -->
  <mat-expansion-panel [disabled]="!solution">
    <mat-expansion-panel-header>
      <mat-panel-title>
        Solution 
      </mat-panel-title>
      <mat-panel-description>
         A solution that is found by BRISE ({{solution ? 'Done' : 'Please stand by..'}})
         <mat-icon>star_rate</mat-icon>
      </mat-panel-description>
    </mat-expansion-panel-header>
    <ng-template matExpansionPanelContent>
      <mat-list class="solution">
        <mat-list-item>
          <mat-icon matListIcon>outlined_flag</mat-icon>
          <span class="desc">Configuration: </span> <span>{{solution.configuration}}</span>
        </mat-list-item>
        <mat-list-item>
          <mat-icon matListIcon>grade</mat-icon>
          <span class="desc">Result: </span> <span>{{solution.result}}</span>
        </mat-list-item>
        <mat-list-item>
          <mat-icon matListIcon>network_check</mat-icon>
          <span class="desc">Deviation result from default: </span> <span>{{100*(solution.result - default_task.result)/default_task.result | number:'2.0-0'}}%</span>
        </mat-list-item>
        <mat-list-item>
          <mat-icon matListIcon>blur_on</mat-icon>
          <span class="desc">Performed measurements: </span> <span>{{solution['performed measurements']}}</span>
        </mat-list-item>
        <mat-list-item>
          <mat-icon matListIcon>sentiment_satisfied_alt</mat-icon>
          <span class="desc">Saved efforts: </span> <span>
            <!--{{-->
              <!--(1 - solution['performed measurements'] / ( 3600 * taskConfig['ExperimentsConfiguration']['MaxRepeatsOfExperiment'])) * 100 |number:'2.0-2'-->
            <!--}}%-->
            {{
              (1 - solution['performed measurements'] / ( taskConfig['DomainDescription']['AllConfigurations'][0].length * taskConfig['DomainDescription']['AllConfigurations'][1].length * taskConfig['DomainDescription']['AllConfigurations'][2].length * taskConfig['DomainDescription']['AllConfigurations'][3].length * taskConfig['DomainDescription']['AllConfigurations'][4].length * taskConfig['DomainDescription']['AllConfigurations'][5].length * taskConfig['DomainDescription']['AllConfigurations'][6].length * taskConfig['DomainDescription']['AllConfigurations'][7].length * taskConfig['ExperimentsConfiguration']['MaxRepeatsOfExperiment'])) * 100 |number:'2.0-2'
            }}%
        </span>
        </mat-list-item>
      </mat-list>
    </ng-template>
  </mat-expansion-panel>
</mat-accordion>

// frontend-new/src/widgets/info-board/ui/InfoBoard.vue
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { storeToRefs } from 'pinia'
// Constant
import { MainEvent } from '../../../entities/main'
import type { Solution } from '../../../entities/task/model/task-data.model';

//service
import { useMainEventStore } from '../../../entities/main'

interface NewsPoint {
    'time': any;
    'message': string;
}

// initialize store
const store = useMainEventStore()
// destructure reactive value from main.event.store
const { experiment_description, searchspace } = storeToRefs(store)

// information log
const news = ref<NewsPoint[]>([])

const solution = ref<Solution>()
const configWithNones = ref('')
const result = ref('')
let default_configuration: any
let sol: any
let dc: any

const duration = 3000
const snackbar = ref(false)
const snackbarMsg = ref('')

function refresh(): void {
    solution.value = undefined
    news.value = []
}

function initMainEvents(): void {
    // Main events
    store.onEvent(MainEvent.DEFAULT)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            let obj = JSON.parse(message.body)
            default_configuration = obj[0]
            let temp: NewsPoint = { 'time': Date.now(), 'message': 'Default configuration results received' }
            snackbarMsg.value = temp['message']
            //news.value.push(temp)
            // snackbar.open(temp['message'], '×', {
            //   duration: 3000
            // });
        }

    });

    store.onEvent(MainEvent.FINAL)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            let obj = JSON.parse(message.body)
            solution.value = obj[0];
            configWithNones.value = JSON.stringify(solution.value?.configurations, null, '\t')
            result.value = JSON.stringify(solution.value?.results)
            sol = Object.values(solution.value?.results || {})
            dc = Object.values(default_configuration.results)
            configWithNones.value = configWithNones.value.replace(",,", ",None,")
            // NewsPOint type everywhere?
            let temp: NewsPoint = {
                'time': Date.now(),
                'message': '★★★ The optimum result is found. The best point is reached ★★★'
            }
            snackbarMsg.value = temp['message']
            news.value.push(temp)
        }
    });

    // For information messages
    store.onEvent(MainEvent.LOG)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'info' || message.headers['message_subtype'] === 'error') {
            let obj = JSON.parse(message.body)
            let temp = { 'time': Date.now(), 'message': obj }
            snackbarMsg.value = temp['message']
            news.value.push(temp)
        }
    });

    // oldValue, newValue?
    watch(experiment_description, () => {
        refresh()
        searchspace.value['size'] = parseFloat(searchspace.value['size'])
        let temp = {
            'time': Date.now(),
            'message': 'The main configurations of the experiment are obtained. Let\'s go! '
        }
        snackbarMsg.value = temp['message']
        news.value.push(temp)
    },
        // reactive object from store, need deep to tracl properties of the object
        { deep: true })
    store.onEvent(MainEvent.NEW)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            let configs = JSON.parse(message.body)
            configs.forEach((configuration: any) => {
                if (configuration) {
                    let temp = {
                        'time': Date.now(),
                        'message': 'New results for ' + JSON.stringify(configuration["configurations"], null, '\t')
                    }
                    snackbarMsg.value = temp['message']
                    news.value.push(temp)
                } else {
                    console.log("Empty configuration")
                }
            })
        }
    });

    store.onEvent(MainEvent.PREDICTIONS)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            let obj = JSON.parse(message.body)
            let temp = {
                'time': Date.now(),
                'message': 'Prediction obtained. ' + obj.length + ' predictions'
            }
            snackbarMsg.value = temp['message']
            news.value.push(temp)
        }
    });
}

onMounted(() => {
    initMainEvents()
})

// decimalPipe alternative
function formatPercent(value: number): string {
    return value.toFixed(2)
}

</script>

<template>
    <v-expansion-panels>
        <!-- Panel 1 -->
        <v-expansion-panel :disabled="news.length === 0">
            <v-expansion-panel-title class="info">
                Info messages

                <v-icon icon="mdi-text-box"></v-icon>

            </v-expansion-panel-title>
            <v-expansion-panel-text>
                Basic information from the workflow of experiments ({{ news ? news.length : "0" }})
            </v-expansion-panel-text>

            <!-- Logs list -->

            <v-list lines="two" v-if="news.length != 0">
                <v-list-item v-for="info in news" :key="info.time" prepend-icon="mdi-check">
                    <v-list-item-title>{{ info.message }}</v-list-item-title>
                    <v-list-item-subtitle>
                        {{ new Date(info.time).toLocaleDateString() }}
                    </v-list-item-subtitle>
                    <v-divider />
                </v-list-item>
            </v-list>
        </v-expansion-panel>

        <!-- Panel 2 -->
        <v-expansion-panel :disabled="!solution">
            <v-expansion-panel-title>
                Solution

                <v-icon icon="mdi-star" />

            </v-expansion-panel-title>
            <v-expansion-panel-text>
                A solution that is found by BRISE ({{ solution ? 'Done' : 'Please stand by..' }})
            </v-expansion-panel-text>
            <v-expansion-panel-text>
                <v-list class="solution" v-if="solution">
                    <v-list-item prepend-icon="mdi-flag">
                        <span class="desc">Configuration: </span> <span>{{ configWithNones }}</span>
                    </v-list-item>

                    <v-list-item prepend-icon="mdi-grade">
                        <span class="desc">Result: </span> <span>{{ result }}</span>
                    </v-list-item>

                    <v-list-item prepend-icon="mdi-network">
                        <span class="desc">Quality gain: </span>
                        <span>{{ formatPercent(100 * (dc[0] - sol[0]) / dc[0]) }}
                            %</span>
                    </v-list-item>

                    <v-list-item prepend-icon="mdi-blur">
                        <span class="desc">Performed measurements: </span>
                        <span>{{ solution['performed_measurements'] }}</span>
                    </v-list-item>

                    <v-list-item v-if="searchspace['size'] != 'Infinity'">
                        <span class="desc">Saved efforts: </span>
                        <span>
                            {{
                                formatPercent((1 - solution['performed_measurements'] /
                                    ((searchspace['size'] as any) *
                                        (experiment_description as any)?.['Repeater']?.['Parameters']?.['MaxTasksPerConfiguration'])
                                ) * 100
                                ) }} %
                        </span>

                    </v-list-item>
                </v-list>
            </v-expansion-panel-text>
        </v-expansion-panel>
    </v-expansion-panels>

    <!-- Snackbar global -->
    <v-snackbar v-model="snackbar" :timeout="duration">
        {{ snackbarMsg }}
    </v-snackbar>
</template>
