// front_end/src/app/components/task-list/task-list.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';

import { MatPaginator, MatTable, MatSort, MatTableDataSource } from '@angular/material';
import { animate, state, style, transition, trigger } from '@angular/animations';

// Service
import {MainEventService} from '../../core/services/main.event.service';


import { Task } from '../../data/taskData.model';

import { MainEvent } from '../../data/client-enums';

import { ExperimentDescription } from '../../data/experimentDescription.model';


@Component({
  selector: 'app-task-list',
  templateUrl: './task-list.component.html',
  styleUrls: ['./task-list.component.scss'],
  animations: [
    trigger('detailExpand', [
      state('collapsed', style({ height: '0px', minHeight: '0', display: 'none' })),
      state('expanded', style({ height: '*' })),
      transition('expanded <=> collapsed', animate('225ms cubic-bezier(0.4, 0.0, 0.2, 1)')),
    ]),
  ],
})
export class TaskListComponent implements OnInit {

  @ViewChild('table') table: MatTable<Element>;
  @ViewChild(MatPaginator) paginator: MatPaginator;
  @ViewChild(MatSort) sort: MatSort;

  stack: Array<any> = []
  result: Array<Task> = []

  focus: any
  displayedColumns: String[] =  ['id', 'run', 'result'];
  experimentDescription: ExperimentDescription
  searchSpaceDescription: Object
  update: boolean

  public resultData: MatTableDataSource<Task>

  constructor(private ioMain: MainEventService) {
    this.resultData = new MatTableDataSource(this.result);

    this.resultData.filterPredicate = (task, filter) => {
      let params: String
      let results: String
      task.run.param.forEach(param => {
        params = params + param
      });
      Object.values(task.meta.result).forEach(result => {
        results = results + String(result)
      });
      const dataStr = task.id +
        params +
        results;
      return dataStr.indexOf(filter) != -1;
    }
  }

  ngOnInit() {
    this.resultData.paginator = this.paginator;
    this.resultData.sort = this.sort;
    this.resultData.sortingDataAccessor = this.sortingDataAccessor;
    this.initMainEvents()

  }

  refresh() {
    this.result = []
    this.resultData = new MatTableDataSource([])
    this.update = true
  }
  clearFocus():void {
    this.focus = null
  }

  applyFilter(filterValue: string) {
    this.resultData.filter = filterValue.trim().toLowerCase();

    if (this.resultData.paginator) {
      this.resultData.paginator.firstPage();
    }
  }

  sortingDataAccessor(data, sortHeaderId) {
    switch (sortHeaderId) {
      case 'id': return data.id ? data.id : null;
      case 'run': return Object.values(data.run.param)[0] ? Object.values(data.run.param)[0] : null;
      case 'result': return Object.values(data.meta.res_config)[0] ? Number(Object.values(data.meta.res_config)[0]) : null;
      default: return data[sortHeaderId];
    }
  }

  searchTasks(search: Array<any>) {
    let search_without_Nones = this.replaceNones(search && Object.values(search))
    let select: Array<Task> = []
    if (arguments.length && this.result.length) {
      this.result.map(task => {
        let paramsValues = this.replaceNones(task.config && Object.values(task.config))
        let count_diff = 0
        for (let i = 0; i < search_without_Nones.length; ++i){
          if (search_without_Nones[i] != paramsValues[i]){
            count_diff = count_diff + 1
          }
        }
        if(count_diff == 0){
          select.push(task)
        }
      })
    }
    return select
  }

  replaceNones(config: Array<any>){
    let res_config = new Array<any>()
    Array.prototype.forEach.call(config, param => {
      if(param == '' || param == null){
        res_config.push('None')
      }
      else{
        res_config.push(param)
      }
    });
    return res_config
  }

  getAverageResult(search: Array<any>) {
    let select = this.searchTasks(search)
    let avg_res:any[] = new Array<any>()
    let sum = new Array<Array<any>>()
    for (let i = 0; i < Object.values(select[0].meta.result).length; i++) {
      sum[i]  = new Array<any>();
    }
    select && select.map(task => {
      for (let i = 0; i < Object.values(task.meta.result).length; i++) {
        task.meta && sum[i].push(Number(Object.values(task.meta.result)[i]))
      }
    })
    for (let i = 0; i < Object.values(select[0].meta.result).length; i++) {
      avg_res[i] = sum[i].reduce((a, b) => a + b, 0)/sum[i].length
    }
    return avg_res
  }

  // --------------------- MainEvents ---------------
  private initMainEvents(): void {
    this.ioMain.onEvent(MainEvent.EXPERIMENT)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'description') {
          this.experimentDescription = JSON.parse(message.body)['experiment_description'];
          this.searchSpaceDescription = JSON.parse(message.body)['searchspace_description'];
          this.update = false
          this.refresh()
        }
      });

    this.ioMain.onEvent(MainEvent.NEW)
      .subscribe((message) => {
        if (message.headers['message_subtype'] === 'task') {
          var fresh: Task = new Task(JSON.parse(message.body))
          var params_array = String(fresh.config).split(',')
          fresh.stub_config = this.replaceNones(params_array)
          // add a new task if it is not in the this.result
          !this.result.includes(fresh, -1) && this.result.push(fresh);
          this.resultData.data = this.result;
        }
      });
  }
}

<div class="box" *ngIf="update">
    <!-- RESULT table -->
    <mat-card class="result">
      <mat-card-header>
        <h3>Result <span class="length">({{result?.length}})</span></h3>
      </mat-card-header>

      <mat-card-content>
        <mat-form-field>
          <input matInput (keyup)="applyFilter($event.target.value)" placeholder="Filter">
        </mat-form-field>
        <div class="mat-elevation-z8" >
          <table mat-table #table [dataSource]="resultData" multiTemplateDataRows matSort>

            <!-- Id Column -->
            <ng-container matColumnDef="id">
              <th mat-header-cell *matHeaderCellDef mat-sort-header> Task ID </th>
              <td mat-cell *matCellDef="let task"> {{task?.id?.toString().substr(0, 8)}} </td>
            </ng-container>

            <!-- Configuration Column -->
            <ng-container matColumnDef="run">
              <th mat-header-cell *matHeaderCellDef mat-sort-header style="padding-left: 20px">
                Configuration
              </th>
              <td mat-cell *matCellDef="let task" style="padding-left: 20px">
                <span *ngFor="let t of task.config | keyvalue; let i = index; let first = first">
                  {{t.key}} = {{t.value}} ;
                </span>
              </td>
            </ng-container>

            <!-- Result Column -->
            <ng-container matColumnDef="result">
                <th mat-header-cell *matHeaderCellDef mat-sort-header style="padding-left: 20px">
                    Result
                  </th>
                  <td mat-cell *matCellDef="let task" style="padding-left: 20px">
                      <li *ngFor="let t of task.roundedResults | keyvalue; let i = index; let first = first">
                          {{t.key}} = {{t.value}} ;
                      </li>
                  </td>
                </ng-container>


            <!-- Expanded Content Column -
              The detail row is made up of this one column that spans across all columns -->
            <ng-container matColumnDef="expandedDetail">
              <td mat-cell *matCellDef="let task" [attr.colspan]="displayedColumns.length">
                <div class="example-element-detail"
                [@detailExpand]="task == focus ? 'expanded' : 'collapsed'" *ngIf="task == focus">
                  <tr>
                  <mat-chip-list selectable="false">
                    <mat-chip *ngFor="let p of task.config | keyvalue; let i = index; let first = first"
                      [selectable]="false">
                      <mat-icon>tune</mat-icon>
                      <span> {{p.key | titlecase}}:</span>
                      <span *ngIf="p.value"> {{p.value}}</span>
                      <span *ngIf="!p.value"> None </span>
                    </mat-chip>
                  </mat-chip-list>
                  </tr>
                  <tr>
                  <mat-list dense role="list">
                    <mat-list-item role="listitem">
                      <mat-icon>rowing</mat-icon>
                      <span>Worker:</span>
                      <span>{{task?.meta?.worker}}</span>
                    </mat-list-item>
                    <mat-list-item role="listitem">
                      <mat-icon>done_all</mat-icon>
                      <span>Repetitions:</span>
                      <span>{{searchTasks(task.config).length}}</span>
                    </mat-list-item>
                    <mat-list-item role="listitem">
                      <mat-icon>settings_ethernet</mat-icon>
                      <span>Average result:</span>
                        <span *ngFor="let res of getAverageResult(task.config); let last = last">
                          {{res | number: '2.1-2'}}
                        <span *ngIf="!last"> ;&nbsp; </span>
                      </span>
                    </mat-list-item>
                  </mat-list>
                  </tr>
                </div>
              </td>
            </ng-container>

            <tr mat-header-row *matHeaderRowDef="displayedColumns;"></tr>
            <tr mat-row *matRowDef="let task; columns: displayedColumns;"
              class="example-element-row"
              [class.example-expanded-row]="focus == task"
              (click)="focus == task ? focus = null : focus = task">
            </tr>
            <tr mat-row *matRowDef="let row; columns: ['expandedDetail']" class="example-detail-row"></tr>
          </table>
          <mat-paginator [pageSizeOptions]="[10, 25, 100]" showFirstLastButtons></mat-paginator>
        </div>

      </mat-card-content>
    </mat-card>  <!-- end results -->

</div>

// frontend/src/widgets/task-list/ui/TaskList.vue
<script setup lang="ts">
import { onMounted, ref, watch, onUnmounted } from 'vue'
import { storeToRefs } from 'pinia'
import { Subscription } from 'rxjs'

import { MainEvent } from '../../../entities/main'
import { Task } from '../../../entities/task/model/task-data.model';
//service
import { useMainEventStore } from '../../../entities/main'

import { normalizeConfigKeys } from '../../../shared/lib'

import { useTaskMetrics } from '../model/task-metrics'


// extract logic from the model layer
const {
    result,
    filteredResult,
    applyFilter,
    replaceNones,
    searchTasks,
    cachedAvg,
    recordBackendResult,
    clearCache
} = useTaskMetrics()

const update = ref(false)

// subscription object for saving and unmounting subscriptions
const subs = new Subscription()
let stopWatch: () => void = () => { }

// initialize store
const store = useMainEventStore()



// destructure reactive value from main.event.store
const { experiment_description } = storeToRefs(store)
function refresh() {
    result.value = []
    update.value = true
    clearCache()
    pendingTasks.length = 0
}


//batching for improving the performance
const pendingTasks: Task[] = []
let intervalId: ReturnType<typeof setInterval>



// alternative for function sortingDataAccessor() in vue (rendering through data-table)

const headers = [
    { title: 'Task ID', key: 'id' },
    {
        title: 'Configuration',
        key: 'run',
        sortRaw: (a: Task, b: Task) => {
            const valA = Object.values(a.config)[0] as string
            const valB = Object.values(b.config)[0] as string
            return valA < valB ? -1 : 1
        }
    },
    {
        title: 'Result',
        key: 'roundedResults',
        sortRaw: (a: Task, b: Task) => {
            const valA = Number(Object.values(a.meta.result)[0])
            const valB = Number(Object.values(b.meta.result)[0])
            return valA - valB
        }
    }
]


function handleConfigurationMessage(message: any): void {
    if (message.headers['message_subtype'] !== 'configuration') return
    const solutions: Array<{ configurations: Record<string, any>, results: Record<string, any> }> = JSON.parse(message.body)
    solutions.forEach(solution => {
        if (solution?.configurations && solution?.results) {
            recordBackendResult(solution.configurations, solution.results)
        }
    })
}

function initMainEvents(): void {
    subs.add(store.onEvent(MainEvent.NEW)?.subscribe((message) => {
        if (message.headers['message_subtype'] === 'task') {
            var fresh: Task = new Task(JSON.parse(message.body))
            var params_array = Object.values(fresh.config)
            fresh.stub_config = replaceNones(params_array)
            // add a new task if it is not in the this.result
            //  !result.value.includes(fresh, -1) && result.value.push(fresh);
            pendingTasks.push(fresh) // only collect, not render yet
        }
        handleConfigurationMessage(message)
    }));

    subs.add(store.onEvent(MainEvent.DEFAULT)?.subscribe(handleConfigurationMessage));
    subs.add(store.onEvent(MainEvent.FINAL)?.subscribe(handleConfigurationMessage));

    stopWatch = watch(experiment_description, () => {

        refresh()
    },
        // reactive object from store, need deep to track properties of the object
        {
            deep: true,
            immediate: true
        })

}

onMounted(() => {
    initMainEvents()

    intervalId = setInterval(() => {
        if (pendingTasks.length === 0) return
        result.value.push(...pendingTasks.splice(0, 20))
    }, 500)

})

onUnmounted(() => {
    clearInterval(intervalId)
    subs.unsubscribe()
    stopWatch()
})
const expanded = ref<string[]>([])


defineExpose({
    replaceNones,
    result,
    pendingTasks
})
</script>

<template>
  <div
    v-if="update"
    class="box"
  >
    <v-card elevation="4">
      <v-card-title>
        <h5>Result <span class="length">({{ result.length }})</span></h5>
      </v-card-title>
      <!--search bar-->
      <v-text-field
        variant="outlined"
        placeholder="Filter"
        @keyup="(e: any) => applyFilter(e.target.value)"
      />

      <v-data-table-virtual
        v-model:expanded="expanded"
        show-expand
        class="result"
        :headers="headers"
        :items="filteredResult"
      >
        <!-- Configuration Column -->
        <template #[`item.run`]="{ item }">
          <span
            v-for="(value, key) in normalizeConfigKeys(item.config)"
            :key="key"
          >
            {{ (key) }} = {{ (value) }} ;
          </span>
        </template>
        <template #[`item.roundedResults`]="{ item }">
          <span
            v-for="(value, key) in normalizeConfigKeys(item.roundedResults)"
            :key="key"
          >
            {{ key }} = {{ value }} ;
          </span>
        </template>


        <!-- Expanded Content Column -->
        <template #expanded-row="{ item }">
          <div v-memo="[item.id, expanded.includes(item.id)]">
            <v-chip
              v-for="(value, key) in normalizeConfigKeys(item.config)"
              :key="key"
            >
              {{ key }}: {{ value }}
            </v-chip>
          </div>

          <v-list>
            <v-list-item>Worker: {{ item.meta.worker }}</v-list-item>
            <v-list-item>Repetitions {{ searchTasks(item.config).length }}</v-list-item>
            <v-list-item>
              Average result:

              <span
                v-for="(res, index) in cachedAvg(item.config)"
                :key="index"
              >
                {{ res.toFixed(2) }}
                <span v-if="index < cachedAvg(item.config).length - 1"> ; </span>
              </span>
            </v-list-item>
          </v-list>
        </template>
      </v-data-table-virtual>
    </v-card>
  </div>
</template>
