// frontend/src/widgets/info-board/ui/InfoBoard.vue
<script setup lang="ts">
import { onMounted, watch, onUnmounted } from 'vue'
import { storeToRefs } from 'pinia'
// Constant
import { MainEvent } from '../../../entities/main'

//service
import { useMainEventStore } from '../../../entities/main'

import { Subscription } from 'rxjs'

import { useInfoBoard } from '../model/use-info-board'
import { normalizeConfigKeys } from '../../../shared/lib'
// initialize store
const store = useMainEventStore()
// destructure reactive value from main.event.store
const { experiment_description } = storeToRefs(store)


const {
  news,
  snackbar,
  snackbarMsg,
  solutionState,
  sol,
  dc,
  default_configuration,
  pushNews,
  triggerSnackbar,
  refresh,
  formatPercent
} = useInfoBoard()



const duration = 3000

const subscriptions = new Subscription()

let stopWatch: () => void = () => { }

function initMainEvents(): void {
  // Main events
  subscriptions.add(store.onEvent(MainEvent.DEFAULT)?.subscribe((message: any) => {
    if (message.headers['message_subtype'] === 'configuration') {
      let obj = JSON.parse(message.body)

      default_configuration.value = obj[0]
      let temp = { 'time': Date.now(), 'message': 'Default configuration results received' }
      triggerSnackbar(temp.message)
      //SpushNews(temp.message)
      // snackbar.open(temp['message'], '×', {
      //   duration: 3000
      // });
    }

  })
  );

  subscriptions.add(store.onEvent(MainEvent.FINAL)?.subscribe((message: any) => {
    if (message.headers['message_subtype'] === 'configuration') {
      let obj = JSON.parse(message.body)
      const s = obj[0]
      const cleanConfigObj = normalizeConfigKeys(s?.configurations ?? {})
      const config = JSON.stringify(cleanConfigObj, null, 2)

      if (!default_configuration.value) {
        console.warn('default_configuration not set yet')
        dc.value = []
        // why should I reset sol too?
        sol.value = []
      } else {
        dc.value = Object.values(default_configuration.value.results)
        sol.value = Object.values(s?.results ?? {})
      }

      solutionState.value = {
        solution: s,
        configWithNones: config,
        result: JSON.stringify(s?.results)
      }
      // NewsPoint type everywhere?
      let temp = {
        'time': Date.now(),
        'message': '★★★ The optimum result is found. The best point is reached ★★★'
      }
      triggerSnackbar(temp.message)
      pushNews(temp.message)

    }
  })
  );

  // For information messages
  subscriptions.add(store.onEvent(MainEvent.LOG)?.subscribe((message: any) => {
    if (message.headers['message_subtype'] === 'info' || message.headers['message_subtype'] === 'error') {
      let obj = JSON.parse(message.body)
      let temp = { 'time': Date.now(), 'message': obj }
      triggerSnackbar(temp.message)
      pushNews(temp.message)
    }
  })
  );

  // oldValue, newValue?
  stopWatch = watch(experiment_description, () => {
    console.log('experiment_description:', JSON.stringify(experiment_description.value, null, 2))
    refresh()
    /* if (searchspace.value && searchspace.value['size']) {
         searchspace.value['size'] = parseFloat(searchspace.value['size'])
     }*/
    let temp = {
      'time': Date.now(),
      'message': 'The main configurations of the experiment are obtained. Let\'s go! '
    }
    triggerSnackbar(temp.message)
    pushNews(temp.message)
  },
    // reactive object from store, need deep to trace properties of the object
    { deep: true })

  subscriptions.add(store.onEvent(MainEvent.NEW)?.subscribe((message: any) => {
    if (message.headers['message_subtype'] === 'configuration') {
      let configs = JSON.parse(message.body)
      configs.forEach((configuration: any) => {
        if (configuration?.configurations) {
          const cleanConfig = normalizeConfigKeys(configuration.configurations)
          const cleanResults = configuration.results ?? {}
          let temp = {
            'time': Date.now(),
            'message': 'New results for ' + JSON.stringify(cleanConfig) + ' → ' + JSON.stringify(cleanResults)
          }
          triggerSnackbar(temp.message)
          pushNews(temp.message)
        } else {
          console.log("Empty configuration")
        }
      })
    }
  })
  );

  // NOTE: main-node does not currently emit a "predictions" message at all, so this handler is presently dead code 
  // pending a rework.
  subscriptions.add(store.onEvent(MainEvent.PREDICTIONS)?.subscribe((message: any) => {
    if (message.headers['message_subtype'] === 'configurations') {
      let obj = JSON.parse(message.body)
      let temp = {
        'time': Date.now(),
        'message': 'Prediction obtained. ' + obj.length + ' predictions'
      }
      triggerSnackbar(temp.message)
      pushNews(temp.message)
    }
  })
  );
}

onMounted(() => {
  initMainEvents()
})

onUnmounted(() => {
  subscriptions.unsubscribe()
  stopWatch()
})



</script>

<template>
  <v-expansion-panels
    elevation="2"
    multiple
  >
    <!-- Panel 1 -->
    <v-expansion-panel :disabled="news.length === 0">
      <v-expansion-panel-title class="info">
        Info messages

        <v-icon
          icon="mdi-text-box"
          class="mx-2"
        />
        <p class="ml-4">
          Basic information from the workflow of experiments ({{ news ? news.length : "0" }})
        </p>
      </v-expansion-panel-title>
      <v-expansion-panel-text>
        <!-- Logs list -->

        <v-list
          v-if="news.length != 0"
          lines="two"
        >
          <v-list-item
            v-for="info in news"
            :key="info.time"
            prepend-icon="mdi-check"
          >
            <v-list-item-title>{{ info.message }}</v-list-item-title>
            <v-list-item-subtitle>
              {{ new Date(info.time).toLocaleDateString() }}
            </v-list-item-subtitle>
            <v-divider />
          </v-list-item>
        </v-list>
      </v-expansion-panel-text>
    </v-expansion-panel>

    <!-- Panel 2 -->
    <v-expansion-panel :disabled="!solutionState.solution">
      <v-expansion-panel-title>
        Solution

        <v-icon icon="mdi-star" />
      </v-expansion-panel-title>
      <v-expansion-panel-text>
        A solution that is found by BRISE ({{ solutionState.solution ? 'Done' : 'Please stand by..' }})
      </v-expansion-panel-text>
      <v-expansion-panel-text>
        <v-list
          v-if="solutionState.solution"
          class="solution"
        >
          <v-list-item prepend-icon="mdi-flag">
            <span class="desc">Configuration: </span> <span>{{ solutionState.configWithNones }}</span>
          </v-list-item>

          <v-list-item prepend-icon="mdi-grade">
            <span class="desc">Result: </span> <span>{{ solutionState.result }}</span>
          </v-list-item>

          <v-list-item
            v-if="dc.length && sol.length"
            prepend-icon="mdi-network"
          >
            <span class="desc">Quality gain: </span>
            <span>{{ formatPercent(100 * (dc[0] - sol[0]) / dc[0]) }}
              %</span>
          </v-list-item>

          <v-list-item prepend-icon="mdi-blur">
            <span class="desc">Performed measurements: </span>
            <span>{{ solutionState.solution['performed_measurements'] }}</span>
          </v-list-item>
        </v-list>
      </v-expansion-panel-text>
    </v-expansion-panel>
  </v-expansion-panels>

  <!-- Snackbar global -->
  <v-snackbar
    v-model="snackbar"
    :timeout="duration"
  >
    {{ snackbarMsg }}
  </v-snackbar>
</template>

// front_end/src/app/components/info-board/info-board.component.ts
import { Component, OnInit } from '@angular/core';
// Material
import { MatSnackBar } from '@angular/material';

// Service
import {MainEventService} from '../../core/services/main.event.service';

// Constant
import { MainEvent } from '../../data/client-enums';
import { Solution } from '../../data/taskData.model';

interface NewsPoint  {
  'time': any;
  'message': string;
}

@Component({
  selector: 'info-board',
  templateUrl: './info-board.component.html',
  styleUrls: ['./info-board.component.scss']
})
export class InfoBoardComponent implements OnInit {
  // Steps for expansion. Material.angular
  panelOpenState = false;

  // Information log
  news: Set<NewsPoint> = new Set()

  solution: Solution
  configWithNones: String
  result: String
  default_configuration: any
  sol: any
  dc: any

  globalConfig: object
  experimentDescription: object
  searchspace: object

  constructor(
    private ioMain: MainEventService,
    public snackBar: MatSnackBar
  ) { }

  ngOnInit() {
    this.initMainEvents()
  }

  refresh(){
    this.solution = undefined
    this.news = new Set()
  }

  private initMainEvents(): void {

    // ----                     Main events
    this.ioMain.onEvent(MainEvent.DEFAULT)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          let obj = JSON.parse(message.body)
          this.default_configuration = obj[0]
          let temp: NewsPoint = {'time': Date.now(), 'message': 'Default configuration results received' }
          this.snackBar.open(temp['message'], '×', {
            duration: 3000
          });
        }
      });

    this.ioMain.onEvent(MainEvent.FINAL)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          let obj = JSON.parse(message.body)
          this.solution = obj[0];
          this.configWithNones = JSON.stringify(this.solution.configurations, null, '\t')
          this.result = JSON.stringify(this.solution.results)
          this.sol = Object.values(this.solution.results)
          this.dc = Object.values(this.default_configuration.results)          
          this.configWithNones = this.configWithNones.replace(",,", ",None,")
          let temp = {
            'time': Date.now(),
            'message': '★★★ The optimum result is found. The best point is reached ★★★'
          }
          this.snackBar.open(temp['message'], '×', {
            duration: 3000
          });
          this.news.add(temp)
        }
      });

    this.ioMain.onEvent(MainEvent.LOG) // For information messages
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'info' || message.headers['message_subtype'] === 'error') {
          let obj = JSON.parse(message.body)
          let temp = {'time': Date.now(), 'message': obj}
          this.snackBar.open(temp['message'], '×', {
            duration: 3000
          });
          this.news.add(temp)
        }
      });

    this.ioMain.onEvent(MainEvent.EXPERIMENT)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'description') {
          let obj = JSON.parse(message.body)
          this.globalConfig = obj['global_configuration']
          this.experimentDescription = obj['experiment_description']
          this.searchspace = obj['searchspace_description']
          this.refresh()
          this.searchspace['size'] = parseFloat(this.searchspace['size'])
          let temp = {
            'time': Date.now(),
            'message': 'The main configurations of the experiment are obtained. Let\'s go! '
          }
          this.snackBar.open(temp['message'], '×', {
            duration: 3000
          });
          this.news.add(temp)
          console.log("Experiment description: ", obj)
          }
      });
    this.ioMain.onEvent(MainEvent.NEW)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          let configs = JSON.parse(message.body)
          configs.forEach(configuration => {
            if (configuration) {
              let temp = {
                'time': Date.now(),
                'message': 'New results for ' + JSON.stringify(configuration["configurations"], null, '\t')
              }
              this.snackBar.open(temp['message'], '×', {
                duration: 3000
              });
              this.news.add(temp)
            } else {
              console.log("Empty configuration")
            }
          })
        }
      });
    this.ioMain.onEvent(MainEvent.PREDICTIONS)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          let obj = JSON.parse(message.body)
          let temp = {
            'time': Date.now(),
            'message': 'Prediction obtained. ' + obj.length + ' predictions'
          }
          this.snackBar.open(temp['message'], '×', {
            duration: 3000
          });
          this.news.add(temp)
        }
      });
  }

}


<mat-accordion>
  <!-- Panel 1 -->
  <mat-expansion-panel [disabled]="!news">
    <mat-expansion-panel-header class="info">
      <mat-panel-title>
        Info messages
      </mat-panel-title>
      <mat-panel-description >
         Basic information from the workflow of experiments ({{news ? news.size : "0"}})
         <mat-icon>
          input
          </mat-icon>
      </mat-panel-description>
    </mat-expansion-panel-header>
    <!-- Logs list  -->
    <ng-template matExpansionPanelContent>
      <mat-list dense role="list" *ngIf=news>
        <mat-list-item role="listitem" *ngFor="let info of news">
          <mat-icon mat-list-icon>done</mat-icon>
          <p mat-line>{{info.message}}</p>
          <mat-divider></mat-divider>
          <p class="time" mat-line> {{info.time | date:'shortTime'}} </p>
        </mat-list-item>
      </mat-list>
    </ng-template>
  </mat-expansion-panel>

  <!-- Panel 2 -->
  <mat-expansion-panel [disabled]="!solution">
    <mat-expansion-panel-header>
      <mat-panel-title>
        Solution
      </mat-panel-title>
      <mat-panel-description>
         A solution that is found by BRISE ({{solution ? 'Done' : 'Please stand by..'}})
         <mat-icon>star_rate</mat-icon>
      </mat-panel-description>
    </mat-expansion-panel-header>
    <ng-template matExpansionPanelContent id="expansion_content">
      <mat-list class="solution" *ngIf="solution">
        <mat-list-item>
          <mat-icon matListIcon>outlined_flag</mat-icon>
          <span class="desc">Configuration: </span> <span>{{solution ? configWithNones : ""}}</span>
        </mat-list-item>
        <mat-list-item>
          <mat-icon matListIcon>grade</mat-icon>
          <span class="desc">Result: </span> <span>{{solution ? result : ""}}</span>
        </mat-list-item>
        <mat-list-item>
          <mat-icon matListIcon>network_check</mat-icon>
          <span class="desc">Quality gain: </span>
          <span>{{solution ? (100 * (dc[0] - sol[0]) / dc[0] | number:'2.0-2') : ""}}
            %</span>
        </mat-list-item>
        <mat-list-item>
          <mat-icon matListIcon>blur_on</mat-icon>
          <span class="desc">Performed measurements: </span>
          <span>{{solution ? solution['performed_measurements'] : ""}}</span>
        </mat-list-item>
        <mat-list-item>
          <mat-icon matListIcon *ngIf="searchspace['size'] != 'Infinity'">sentiment_satisfied_alt</mat-icon>
          <span class="desc" *ngIf="searchspace['size'] != 'Infinity'">Saved efforts: </span> 
          <span *ngIf="searchspace['size'] != 'Infinity'">
            {{
            (1 - solution['performed_measurements'] / (searchspace['size']
              * experimentDescription['Repeater']['Parameters']['MaxTasksPerConfiguration'])) * 100 |number:'2.0-2'
            }}%
        </span>
        </mat-list-item>
      </mat-list>
    </ng-template>
  </mat-expansion-panel>
</mat-accordion>
