// front_end/src/app/components/charts/heat-map-reg/heat-map-reg.component.ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';

// Service
import {MainEventService} from '../../../core/services/main.event.service';

// Model
import { MainEvent } from '../../../data/client-enums';
import { ExperimentDescription } from '../../../data/experimentDescription.model';

// Plot
import { PlotType as type } from '../../../data/client-enums';
import { Color as colors } from '../../../data/client-enums';
import { Smooth as smooth } from '../../../data/client-enums';

import { Solution } from '../../../data/taskData.model';


@Component({
  selector: 'hm-reg',
  templateUrl: './heat-map-reg.component.html',
  styleUrls: ['./heat-map-reg.component.scss']
})
export class HeatMapRegComponent implements OnInit {

  // Variables
  prediction = new Map()
  solution: Solution
  measPoints: Array<Array<any>> = []

  resetRes() {
    this.prediction.clear()
    this.solution = undefined
    this.measPoints = []
  }

  @ViewChild('reg') reg: ElementRef;

  globalConfig: object
  experimentDescription: ExperimentDescription
  searchspace: object
  // Rendering axises
  y: Array<any>
  x: Array<any>

  // Default theme
  theme = {
    type: type[0],
    color: colors[0],
    smooth: smooth[0]
  }
  public type = type
  public colors = colors
  public smooth = smooth

  constructor(private ioMain: MainEventService) {
  }

  ngOnInit() {
    this.initMainConnection();
    // window.onresize = () => Plotly.relayout(this.reg.nativeElement, {})
  }

  isModelType(type: String) {
    return this.experimentDescription && this.experimentDescription.Predictor.models[0].Type == type
  }

  // Rendering
  regrRender(): void {
    let regression = this.reg.nativeElement
    const data = [
      {
        z: this.zParser(this.prediction),
        x: this.x,
        y: this.y,
        type: this.theme.type,
        colorscale: this.theme.color,
        zsmooth: this.theme.smooth
      },
      {
        type: 'scatter',
        mode: 'markers',
        name: 'measured points',
        marker: { color: 'grey', size: 8, symbol: 'x' },
        x: this.measPoints.map(arr => arr[1]),
        y: this.measPoints.map(arr => arr[0])
      },
      {
        type: 'scatter',
        mode: 'markers',
        name: 'solution',
        marker: { color: 'Gold', size: 16, symbol: 'star' },
        x: this.solution && [this.solution.configurations[1]],
        y: this.solution && [this.solution.configurations[0]]
      }
    ];

    var layout = {
      title: 'Regression',
      autosize: true,
      showlegend: false,
      xaxis: { title: "Threads",
        type: 'category',
        autorange: true,
        range: [Math.min(...this.x), Math.max(...this.x)]
      },
      yaxis: { title: "Frequency",
        type: 'category',
        autorange: true,
        range: [Math.min(...this.y), Math.max(...this.y)]  }
    };

    Plotly.react(regression, data, layout);
  }
  zParser(data: Map<String, any>): Array<Array<any>> {
    var z = []
    this.y.forEach(y => {
      var row = []
      this.x.forEach(x => {
        row.push(data.get(String([y, x]))[0]) // change [x,y] or [y,x] if require horizontal or vertical orientation
                                          // Get the first result from an array
      });
      z.push(row)
    });
    return z
  }

  // Init conection
  private initMainConnection(): void {
    // ---- Main events

    this.ioMain.onEvent(MainEvent.FINAL)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          let configs = JSON.parse(message.body)
          if (configs.length > 1) console.log("WARNING! More than one solution received!")
          let result = configs[0]
          if (result) {
              this.solution = result // In case if only one point solution
              this.measPoints.push(result['configurations'])
              console.log("Measured", this.measPoints.length)
              this.prediction.size && this.regrRender()
            } else { console.log("Empty solution") }
        }
      });

    this.ioMain.onEvent(MainEvent.EXPERIMENT)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'description') {
          const obj = JSON.parse(message.body);
          this.resetRes();
          this.globalConfig = obj['global_configuration'];
          this.experimentDescription = obj['experiment_description'];
          this.searchspace = obj['searchspace_description'];
          let boundaryObj: Object;
          boundaryObj = this.searchspace['boundaries'];
          this.x = Object.values(boundaryObj)[1];
          this.y = Object.values(boundaryObj)[0];
        }
      });

    this.ioMain.onEvent(MainEvent.PREDICTIONS)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          const configs = JSON.parse(message.body)
          configs.forEach(point => {
            if (point) {
              this.prediction.set(String(point['configurations']), point['results']);
            } else {
              console.log('Empty prediction point')
            }
          });
          console.log(' Prediction points:', configs.length);
          this.prediction.size && this.regrRender();
        }
      });

  }

}

// frontend/src/widgets/charts/heatmap-reg/ui/HeatmapReg.vue
<script setup lang="ts">
import { ref, onMounted, watch, computed, nextTick, onUnmounted } from 'vue'
import { storeToRefs } from 'pinia'
import { Color, PlotType, Smooth } from '../../model/chart.types'
import { useMainEventStore, MainEvent } from '../../../../entities/main'
import type { Solution } from '../../../../entities/task/model/task-data.model'
import { DataTransformer } from '../../../../entities/experiment/lib/data.transformer'
import { cleanIdentifier } from '../../../../shared/lib'
const store = useMainEventStore()
const { experiment_description, searchspace, globalConfig } = storeToRefs(store)

const solution = ref<Solution | null>(null)
const result = ref(new Map<string, any>())
const prediction = ref(new Map<string, any>())
const measPoints = ref<Array<[any, any]>>([])


const x = ref<string[]>([])
const y = ref<string[]>([])
const xTitle = ref<string>('X Axis')
const yTitle = ref<string>('Y Axis')
const xParamKey = ref<string>('')
const yParamKey = ref<string>('')
const map = ref<HTMLElement | null>(null)

const theme = ref({
    type: PlotType[0] as string,
    color: Color[0] as string,
    smooth: Smooth[0] as string | boolean
})
const colors = Color
const types = PlotType

function resetRes() {
    result.value.clear()
    prediction.value.clear()
    measPoints.value = []
    solution.value = null
}

const isModelType = computed(() => {
    if (!experiment_description.value) return 'unknown'
    const exp = experiment_description.value as any
    const model = exp.ConfigurationSelection?.Predictor?.Model
    return !!model?.Surrogate?.Instance?.LinearRegression ? 'regression' : 'unknown'
})


const zMatrix = computed(() => {
    return DataTransformer.buildZMatrix(x.value, y.value, prediction.value)
})


const optimumPoint = computed(() => {
    if (!solution.value) return null

    const configs = (solution.value as any).configurations
    const rawXVal = configs?.[xParamKey.value]
    const rawYVal = configs?.[yParamKey.value]


    const cleanX = cleanIdentifier(rawXVal)
    const cleanY = cleanIdentifier(rawYVal)


    const xExists = x.value.includes(cleanX)
    const yExists = y.value.includes(cleanY)



    if (!cleanX || !cleanY || !xExists || !yExists) {
        console.warn('Optimum point is out of axis bounds or invalid:', { cleanX, cleanY })
        return null
    }

    return { x: cleanX, y: cleanY }
})

let retryCount = 0
const MAX_RETRIES = 60

async function render(): Promise<void> {
    const Plotly = store.plotlyInstance
    if (!Plotly || isModelType.value !== 'regression' || !map.value) return
    if (prediction.value.size === 0 && !solution.value) return


    if (map.value.clientHeight === 0 || map.value.clientWidth === 0) {
        retryLayout()
        return
    }

    retryCount = 0
    // layer 1: heatmap
    const data: any[] = [
        {
            z: zMatrix.value,
            x: x.value,
            y: y.value,
            type: theme.value.type,
            colorscale: theme.value.color,
            zsmooth: theme.value.smooth
        }
    ]

    // layer 2: find optimum
    if (optimumPoint.value) {
        data.push({
            type: 'scatter',
            mode: 'markers',
            name: 'Optimum',
            hoverinfo: 'text',
            hovertext: `Optimum:<br>${xTitle.value}: ${optimumPoint.value.x}<br>${yTitle.value}: ${optimumPoint.value.y}`,
            marker: { color: 'Gold', size: 18, symbol: 'star', line: { color: 'black', width: 1.5 } },
            x: [optimumPoint.value.x],
            y: [optimumPoint.value.y],
            cliponaxis: false
        })
    }

    const layout: any = {
        margin: { l: 70, r: 40, t: 50, b: 80 },
        title: { text: 'Surrogate Model Surface (Regression)' },
        autosize: true,
        showlegend: false,
        xaxis: {
            title: { text: xTitle.value },
            type: 'category',
            categoryorder: 'array',
            categoryarray: x.value,

            range: [-0.5, x.value.length - 0.5],
            automargin: true
        },
        yaxis: {
            title: { text: yTitle.value },
            type: 'category',
            categoryorder: 'array',
            categoryarray: y.value,
            range: [-0.5, y.value.length - 0.5],
            automargin: true
        }
    }


    await Plotly.react(map.value, data, layout, { responsive: true })
}

function retryLayout() {
    if (retryCount++ < MAX_RETRIES) {
        requestAnimationFrame(() => render())
    } else {
        console.error('[Heatmap-Reg] Container never got layout, giving up')
        retryCount = 0
    }
}

let resizeObserver: ResizeObserver | null = null

onMounted(() => {
    initMainEvents()
    resizeObserver = new ResizeObserver(() => {
        if (map.value && map.value.clientHeight > 0) render()
    })
    if (map.value) resizeObserver.observe(map.value)
}
)

onUnmounted(() => {
    resizeObserver?.disconnect()
    resizeObserver = null
})

function initMainEvents() {
    store.onEvent(MainEvent.PREDICTIONS)?.subscribe(async (message: any) => {
        console.log('[Heatmap Debug] PREDICTIONS event received', message)
        const preds = JSON.parse(message.body)
        for (const item of preds) {
            if (item && item.configurations) {
                const rawXVal = item.configurations[xParamKey.value]
                const rawYVal = item.configurations[yParamKey.value]

                const cleanX = cleanIdentifier(rawXVal)
                const cleanY = cleanIdentifier(rawYVal)

                prediction.value.set(`${cleanY},${cleanX}`, item['results'])
            }
        }

        nextTick(() => render())

    })


    watch([experiment_description, searchspace], () => {
        console.log('[Heatmap-Reg] searchspace RAW', JSON.stringify(searchspace.value))
        if (!experiment_description.value || !searchspace.value || !globalConfig.value) return
        resetRes()

        const boundaryObj = searchspace.value?.boundaries?.[0]?.Boundaries
        console.log('[Heatmap-Reg] boundaryObj FULL', JSON.stringify(boundaryObj, null, 2))
        console.log('[Heatmap-Reg] boundaryObj KEYS', Object.keys(boundaryObj ?? {}))
        if (!boundaryObj) return

        const keys = Object.keys(boundaryObj).filter(k => k !== 'root')
        if (keys.length >= 2) {
            xParamKey.value = keys[0]
            yParamKey.value = keys[1]
            xTitle.value = cleanIdentifier(keys[0])
            yTitle.value = cleanIdentifier(keys[1])


            const rawX = boundaryObj[keys[0]] ?? []
            const rawY = boundaryObj[keys[1]] ?? []


            y.value = rawY.map((item: any) => cleanIdentifier(item))
            x.value = rawX.map((item: any) => cleanIdentifier(item))
        }
    }, { deep: true, immediate: true })

    watch([result, prediction, measPoints, solution], () => nextTick(() => render()), { deep: true })


    store.onEvent(MainEvent.FINAL)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            const configs = JSON.parse(message.body)
            const res = configs?.[0]
            if (res) {

                solution.value = res
                measPoints.value.push(res['configurations'])
            }
            if (prediction.value.size > 0) {
                nextTick(() => render())
            }
        }
    })
}
</script>

<template>
    <div v-if="isModelType === 'regression'">
        <div ref="map" class="heatmap-container" />
    </div>
    <select v-model="theme.color" @change="render">
        <option v-for="col in colors" :key="col" :value="col"></option>
    </select>
</template>

<style scoped>
.heatmap-container {
    min-height: 500px;
    width: 100%;
}
</style>
