// frontend/src/widgets/charts/imp-res/ui/ImpRes.vue
<script setup lang="ts">
import { ref, onMounted, watch, nextTick } from 'vue'
import { storeToRefs } from 'pinia'

import { MainEvent } from '../../../../entities/main'
import type { Solution } from '../../../../entities/task/model/task-data.model';

//service
import { useMainEventStore } from '../../../../entities/main'

import { useResultTracker } from '../model/result-calc'

interface PointExp {
    configurations: Array<any>;
    results: Array<any>;
    time: any;
    'measured points': number;
}
// initialize store
const store = useMainEventStore()
// destructure reactive value from main.event.store
const { experiment_description } = storeToRefs(store)


const isChartInitialized = ref(false)

let solution: Solution

const isVisible = ref(false)

const { allRes, bestRes, reset, pushInitial, pushTracked } = useResultTracker()

const impr = ref<HTMLElement | null>(null)

onMounted(() => {
    initMainEvents()
})

async function render() {
    // DOM element. Render point

    const element = impr.value
    const Plotly = store.plotlyInstance
    if (!element || !Plotly) return
    isVisible.value = true
    await nextTick()


    // X-axis data
    const xBest = Array.from(bestRes.value).map((i: any) => i['measured points']);
    // Results
    const yBest = Array.from(bestRes.value).map((i: any) => i['results'][0]);

    const allResultSet = { // Data for all results
        x: Array.from(allRes.value).map((i: any) => i['measured points']),
        y: Array.from(allRes.value).map((i: any) => i['results'][0]),
        type: 'scattergl' as const,
        mode: 'lines+markers' as const,
        line: { color: 'rgba(67,67,67,1)', width: 1, shape: 'spline' as const, dash: 'dot' as const },
        text: Array.from(allRes.value).map((i: any) => String(i['configurations'])),
        marker: {
            color: 'rgba(255,64,129,1)',
            size: 8,
            symbol: 'x' as const
        },
        name: 'results'
    };
    const bestPointSet = { // Data for the best available results
        x: xBest,
        y: yBest,
        type: 'scattergl' as const,
        mode: 'lines+markers' as const,
        line: { color: 'rgba(67,67,67,1)', width: 2, shape: 'spline' as const },
        name: 'best point',
        marker: { size: 6, symbol: 'x' as const, color: 'rgba(67,67,67,1)' }
    };

    const startEndPoint = { // Start & Finish markers
        x: [xBest[0], xBest[xBest.length - 1]],
        y: [yBest[0], yBest[yBest.length - 1]],
        type: 'scattergl' as const,
        mode: 'markers' as const,
        hoverinfo: 'none' as const,
        showlegend: false,
        marker: { color: 'rgba(255,64,129,1)', size: 10 }
    };

    const data = [allResultSet, bestPointSet, startEndPoint];

    const layout = {
        title: { text: 'The best results' } as const,
        showlegend: true,
        autosize: true,
        xaxis: {
            title: { text: 'Sequence number' } as const,
            showline: true,
            showgrid: false,
            zeroline: false,
            showticklabels: true,
            linecolor: 'rgb(204,204,204)',
            linewidth: 2,
            autotick: false,
            ticks: 'outside' as const,
            tickcolor: 'rgb(204,204,204)',
            tickwidth: 2,
            ticklen: 5,
            tickfont: {
                family: 'Roboto',
                size: 12,
                color: 'rgb(82, 82, 82)'
            }
        },
        yaxis: {
            title: { text: Object.values(experiment_description.value?.Context?.TaskConfiguration?.Objectives ?? {})[0]?.Name ?? '' } as const,
            showgrid: false,
            zeroline: false,
            showline: true,
            linecolor: 'rgb(204,204,204)',
            showticklabels: true,
            ticks: 'outside' as const,
            tickcolor: 'rgb(204,204,204)',
            ticklen: 5,
            tickfont: {
                family: 'Roboto',
                size: 12,
                color: 'rgb(82, 82, 82)'
            }
        },
    };
    if (element)
        Plotly.react(element, data, layout);
}


function initMainEvents() {
    watch(experiment_description, () => {
        reset()
        // pointer to dom element 
        const element = impr.value
        isVisible.value = false
        isChartInitialized.value = false
        const Plotly = store.plotlyInstance
        // will clear the div, and remove any Plotly plots that have been placed in it
        if (element && Plotly) {
            Plotly.purge(element)
        }
    }, {
        deep: true,
        immediate: true
    })

    // add start point
    store.onEvent(MainEvent.DEFAULT)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            const configs = JSON.parse(message.body)
            configs.forEach((configuration: any) => {
                solution = configuration
                pushInitial(configuration)
            })
            // render when chart is initialized
            isVisible.value = true
            nextTick(() => {
                render().then(() => { isChartInitialized.value = true })
            })
            // render() // render chart when all points got
        }
    })

    // add last point
    store.onEvent(MainEvent.FINAL)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            const configs = JSON.parse(message.body);
            configs.forEach((configuration: any) => {
                solution = configuration;
                pushInitial(configuration)
            });
            isVisible.value = true
            nextTick(() => {
                render()
            })
        }
    })

    // add new point
    store.onEvent(MainEvent.NEW)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            const configs = JSON.parse(message.body);

            // check the best availbale point
            const descr = experiment_description.value

            let objectives = descr?.['Context']?.['TaskConfiguration']?.['Objectives'] as any
            if (!objectives) return
            const firstObjectiveKey = Object.keys(objectives)[0]
            console.log('TaskConfig', descr?.['TaskConfiguration'])
            const isMinimization = objectives?.[firstObjectiveKey]?.['Minimization']


            configs.forEach((configuration: any) => {
                const min = new Date().getMinutes();
                const sec = new Date().getSeconds();
                // number der measuret points before pushing into an array
                const currentPointIndex = allRes.value.length + 1;

                allRes.value.push({
                    'configurations': Object.values(configuration.configurations),
                    'results': Object.values(configuration.results),
                    'time': min + 'm ' + sec + 's',
                    'measured points': currentPointIndex
                }) // add new point (resut)

                const temp: PointExp = {
                    'configurations': Object.values(configuration.configurations),
                    'results': Object.values(configuration.results),
                    'time': min + 'm ' + sec + 's',
                    'measured points': currentPointIndex
                }

                // compare to the last best point
                const lastBest = bestRes.value.at(-1)
                if (lastBest) {
                    const isBetter = isMinimization ? temp.results[0] < lastBest.results[0] : temp.results[0] > lastBest.results[0]
                    if (!isBetter) {
                        temp.results = lastBest.results
                        temp.configurations = lastBest.configurations
                    }
                }

                bestRes.value.push(temp) // add the best availbale point(result) 

            })
            isVisible.value = true
            nextTick(() => {
                render()
            })
        }

    })
}





</script>

<template>
  <div
    v-show="isVisible"
    ref="impr"
  />
</template>

// front_end/src/app/components/charts/imp-res/imp-res.component.ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';

// Service
import {MainEventService} from '../../../core/services/main.event.service';

import { Solution } from '../../../data/taskData.model';
import { MainEvent } from '../../../data/client-enums';

import { ExperimentDescription } from '../../../data/experimentDescription.model';

interface PointExp {
  configurations: Array<any>;
  results: Array<any>;
  time: any;
  'measured points': number;
}

@Component({
  selector: 'imp-res',
  templateUrl: './imp-res.component.html',
  styleUrls: ['./imp-res.component.scss']
})
export class ImpResComponent implements OnInit {
  // The experiments results
  bestRes = new Set<PointExp>();
  allRes = new Set<PointExp>();
  // Best point
  solution: Solution;

  experimentDescription: ExperimentDescription;

  // poiner to DOM element #map
  @ViewChild('improvement') impr: ElementRef;

  constructor(private ioMain: MainEventService) {
  }

  ngOnInit() {
    this.initMainEvents();
    window.onresize = () => this.bestRes.size > 2 && this.render();
  }
  // --------------------------   Main-node
  private initMainEvents(): void {
    this.ioMain.onEvent(MainEvent.EXPERIMENT)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'description') {
          this.bestRes.clear();
          this.allRes.clear();
          const element = this.impr.nativeElement;
          element.style.display = 'none';
          Plotly.purge(element);
          this.solution = undefined;
          this.experimentDescription = JSON.parse(message.body)['experiment_description'];
        }
      });

    this.ioMain.onEvent(MainEvent.FINAL)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          const configs = JSON.parse(message.body);
          configs.forEach(configuration => {
            this.solution = configuration;
            const min = new Date().getMinutes();
            const sec = new Date().getSeconds();
            const temp: PointExp = {
              'configurations': Object.values(configuration.configurations),
              'results': Object.values(configuration.results),
              'time': min + 'm ' + sec + 's',
              'measured points': this.allRes.size + 1
            };
            this.allRes.add(temp);
            this.bestRes.add(temp); // There is no check if this solution is the best decision
          });
        }
        this.render(); // Render chart when all points got
      });

    this.ioMain.onEvent(MainEvent.DEFAULT).subscribe((message: any) => {
      if (message.headers['message_subtype'] === 'configuration') {
        const configs = JSON.parse(message.body);
        configs.forEach(configuration => {
          this.solution = configuration;
          const min = new Date().getMinutes();
          const sec = new Date().getSeconds();
          const temp: PointExp = {
            'configurations': Object.values(configuration.configurations),
            'results': Object.values(configuration.results),
            'time': min + 'm ' + sec + 's',
            'measured points': this.allRes.size + 1
          };
          this.allRes.add(temp);
          this.bestRes.add(temp); // There is no check if this solution is the best decision
        });
        this.render(); // Render chart when all points got
      }
    });

    this.ioMain.onEvent(MainEvent.NEW)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          const configs = JSON.parse(message.body);
          configs.forEach(configuration => {
            const min = new Date().getMinutes();
            const sec = new Date().getSeconds();
            this.allRes.add({
              'configurations': Object.values(configuration.configurations),
              'results': Object.values(configuration.results),
              'time': min + 'm ' + sec + 's',
              'measured points': this.allRes.size + 1
            }); // Add new point(result)
            const temp: PointExp = {
              'configurations': Object.values(configuration.configurations),
              'results': Object.values(configuration.results),
              'time': min + 'm ' + sec + 's',
              'measured points': this.allRes.size
            };
            // Check the best available point
            const descr = this.experimentDescription;
            this.bestRes && this.bestRes.forEach(function (resItem) {
              // TODO: Max or min from task
              let objPriorities = descr['TaskConfiguration']['ObjectivesPriorities']
              let topObjectiveIdx = objPriorities.indexOf(Math.max(...objPriorities))
              let isMinimization = descr['TaskConfiguration']['ObjectivesMinimization'][topObjectiveIdx]
              if (isMinimization === true) {
                if (temp.results[0] > resItem.results[0]) { // check FIRST result from array!
                  temp.results = resItem.results;
                  temp.configurations = resItem.configurations;
                }
              } else {
                if (temp.results[0] < resItem.results[0]) { // check FIRST result from array!
                  temp.results = resItem.results;
                  temp.configurations = resItem.configurations;
                }
              }
            });
            this.bestRes.add(temp); // Add the best available point(result)
          });
          this.bestRes.size > 2 && this.render();
        }
      });
  }

  render() {
    // DOM element. Render point
    const element = this.impr.nativeElement;
    element.style.display = 'block';
    // X-axis data
    const xBest = Array.from(this.bestRes).map(i => i['measured points']);
    // Results
    const yBest = Array.from(this.bestRes).map(i => i['results'][0]);

    const allResultSet = { // Data for all results
      x: Array.from(this.allRes).map(i => i['measured points']),
      y: Array.from(this.allRes).map(i => i['results'][0]),
      type: 'scatter',
      mode: 'lines+markers',
      line: {color: 'rgba(67,67,67,1)', width: 1, shape: 'spline', dash: 'dot'},
      text: Array.from(this.allRes).map(i => String(i['configurations'])),
      marker: {
        color: 'rgba(255,64,129,1)',
        size: 8,
        symbol: 'x'
      },
      name: 'results'
    };
    const bestPointSet = { // Data for the best available results
      x: xBest,
      y: yBest,
      type: 'scatter',
      mode: 'lines+markers',
      line: {color: 'rgba(67,67,67,1)', width: 2, shape: 'spline'},
      name: 'best point',
      marker: {size: 6, symbol: 'x', color: 'rgba(67,67,67,1)'}
    };

    const startEndPoint = { // Start & Finish markers
      x: [xBest[0], xBest[xBest.length - 1]],
      y: [yBest[0], yBest[yBest.length - 1]],
      type: 'scatter',
      mode: 'markers',
      hoverinfo: 'none',
      showlegend: false,
      marker: {color: 'rgba(255,64,129,1)', size: 10}
    };

    const data = [allResultSet, bestPointSet, startEndPoint];

    const layout = {
      title: 'The best results',
      showlegend: true,
      autosize: true,
      xaxis: {
        title: 'Sequence number',
        showline: true,
        showgrid: false,
        zeroline: false,
        showticklabels: true,
        linecolor: 'rgb(204,204,204)',
        linewidth: 2,
        autotick: false,
        ticks: 'outside',
        tickcolor: 'rgb(204,204,204)',
        tickwidth: 2,
        ticklen: 5,
        tickfont: {
          family: 'Roboto',
          size: 12,
          color: 'rgb(82, 82, 82)'
        }
      },
      yaxis: {
        title: this.experimentDescription['TaskConfiguration']['Objectives'][0],
        showgrid: false,
        zeroline: false,
        showline: true,
        linecolor: 'rgb(204,204,204)',
        showticklabels: true,
        ticks: 'outside',
        tickcolor: 'rgb(204,204,204)',
        ticklen: 5,
        tickfont: {
          family: 'Roboto',
          size: 12,
          color: 'rgb(82, 82, 82)'
        }
      },
    };

    Plotly.react(element, data, layout);
  }

}

<!-- <mat-slide-toggle [checked]="isRenderAllRes" (change)="render()">All results</mat-slide-toggle> -->
<div #improvement>
    
</div>
