// front_end/src/app/components/charts/multi-dim/multi-dim.component.ts
import { Component, OnInit, ElementRef, ViewChild } from '@angular/core';

// Service
import {MainEventService} from '../../../core/services/main.event.service';

import { MainEvent } from '../../../data/client-enums';
import { ExperimentDescription } from '../../../data/experimentDescription.model';
import { Solution } from '../../../data/taskData.model';

interface PointExp {[Key: string]: any}

@Component({
  selector: 'multi-dim',
  templateUrl: './multi-dim.component.html',
  styleUrls: ['./multi-dim.component.scss']
})
export class MultiDimComponent implements OnInit {

  // Experiment configurations
  experimentDescription: ExperimentDescription
  searchspace: object
  resultParamsRange: any // Map. results parameters with possible ranges
  parameter_names: any
  keyParam: any
  rootParam: any
  currentDiagram: any
  experiment: any

  // Best point
  allPoints = new Set<PointExp>()
  // Default point
  defaultPoint: PointExp

  // Proposed solution from model
  solution: Solution

  resetRes() {
    this.experimentDescription = undefined
    this.defaultPoint = undefined
    this.allPoints.clear()
    this.solution = undefined
  }


  constructor(
    private ioMain: MainEventService,
  ) { }

  ngOnInit() {
    this.initMainEvents();
  }

  isModelType(type: String) {
    // used in HTML template
    return this.experimentDescription && this.experimentDescription.Predictor.models[0].Type == type
  }

  // --------------------------   Main-node
  private initMainEvents(): void {

    //                            Main events
    this.ioMain.onEvent(MainEvent.EXPERIMENT)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'description') {
          let obj = JSON.parse(message.body)
          this.resetRes()
          this.experimentDescription = obj['experiment_description']
          this.searchspace = obj['searchspace_description']
          this.rootParam = this.searchspace["root_parameters_list"]
          this.experiment = this.searchspace["name"]
          let priorities = this.experimentDescription["TaskConfiguration"]["ObjectivesPriorities"]
          let i = priorities.indexOf(Math.max(...priorities));
          this.keyParam = this.experimentDescription["TaskConfiguration"]["Objectives"][i]
        }

      });

    this.ioMain.onEvent(MainEvent.DEFAULT) // Default configuration
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          let configs = JSON.parse(message.body)
          configs.forEach(configuration => {
            if (configuration) {
              this.chose(configuration)
              this.defaultPoint = configuration // In case if only one point default
              var alphas = new Array();;
              this.parameter_names.forEach(key => {
                alphas.push(configuration.configurations[key])
              })
              let point = this.zip(this.parameter_names, alphas)
              point.set('result', configuration.results[this.keyParam])
              this.allPoints.add(point)
              this.render()
            } else {
              console.log("Empty default")
            }
          })
          console.log('Default:', configs)
        }
      });

    this.ioMain.onEvent(MainEvent.NEW) // New task results
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          let configs = JSON.parse(message.body)
          configs.forEach(configuration => {
        if (configuration) {
            this.chose(configuration)
            var alphas = new Array();;
            this.parameter_names.forEach(key => {
              alphas.push(configuration.configurations[key])
            })
            let point = this.zip(this.parameter_names, alphas)
            point.set('result', configuration.results[this.keyParam])
            this.allPoints.add(point)
            this.render()
          }
          else {
            console.log("Empty task")
          }
          })
        }
      });
    this.ioMain.onEvent(MainEvent.FINAL) // The final configuration, suggested by BRISE.
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          let configs = JSON.parse(message.body)
          configs.forEach(configuration => {
            if (configuration) {
              this.solution = configuration // In case if only one point solution
              console.log('Final:', configs)
            } else {
              console.log("Empty solution")
            }
          })
        }
      });
  }

  render(){
    const element = document.getElementById(this.currentDiagram)
    var trace = [{
      type: 'parcoords',
      line: {
        showscale: true,
        // reversescale: true,
        colorscale: 'Jet',
        color: this.unpack(this.allPoints, 'result')
      },
      dimensions: this.dimmensionsData()
    }];

    var layout = {
      title: {
        text: this.currentDiagram,
        font: {
          size: 20
        },
        xref: 'paper',
        x: 0.05,
      }
    }

    Plotly.react(element, trace, layout)
  }

  dimmensionsData() {
    let data = [] // accommodate dimensional obj
    this.resultParamsRange.size && this.resultParamsRange.forEach((range: Array<any>, param: String)=>{
      if (param != this.experiment){
        let dim = this.factoryDimension(param, range) // make dimensional object through all results by one parameter
        data.push(dim) // add new dimension object for plotting
      }
    })
    return data
  }
  factoryDimension(parameter: String, valuesRange: Array<any> = null) {
    let dimValues = this.unpack(this.allPoints, parameter)
    let dim: any = {
      values: dimValues,
      label: parameter.replace(/_/g, " ")
    }
    // If values are not numerical.
    if (valuesRange && (typeof valuesRange[0] == "string" || typeof valuesRange[0] == "boolean")) {
      dim.tickvals = Array.from(Array(valuesRange.length).keys())
      dim.ticktext = valuesRange
      dim.values = dimValues.map(value => dim.tickvals[dim.ticktext.indexOf(value)])
    }
    return dim
  }
  // Returns an array of values by key from all dictionaries
  unpack(set, key) {
    let selection = []
    set.forEach(point=>{  // point is key value store - Map
      selection.push(point.get(key));
    });
    return selection
  }
  // merge key and values arrays in key
  zip(keys:Array<any>, values:Array<any>) {
    let result = new Map()
    if (keys.length == values.length) {
      keys.forEach((key, i) => result.set(key, values[i]))
    }
    return result
  }
  chose(configuration){
    this.currentDiagram = configuration.configurations[this.experiment]
    let index = this.rootParam.indexOf(this.currentDiagram)
    this.parameter_names = Object.keys(this.searchspace["boundaries"][index]["Boundaries"])
    let rangeValues = Object.values(this.searchspace["boundaries"][index]["Boundaries"])
    this.resultParamsRange = this.zip(this.parameter_names, rangeValues)
    this.resultParamsRange.set('result', undefined) // range for results is undefined
  }
}

<li *ngFor="let item of rootParam">
  <mat-card *ngIf="isModelType('brise.TreeParzenEstimator')">
    <div id={{item}}></div>
  </mat-card>
</li>

// frontend-new/src/widgets/charts/multi-dim/ui/MultiDim.vue
<script setup lang="ts">
import { ref, onMounted, watch, onUnmounted } from 'vue'
import { storeToRefs } from 'pinia'

// Plotly
import Plotly from 'plotly.js-dist-min'


// Constant
import { MainEvent } from '../../../../entities/main'
import type { Solution } from '../../../../entities/task/model/task-data.model';

//service
import { useMainEventStore } from '../../../../entities/main'


// initialize store
const store = useMainEventStore()
// destructure reactive value from main.event.store
const { experiment_description, searchspace } = storeToRefs(store)

// experiment configuration
const parameter_names = ref()
const currentDiagram = ref()
let experiment: string = ''
const rootParam = ref<any[]>([])
let resultParamsRange = ref<Map<string, any>>()
let keyParam = ref('')

//best point 
const allPoints = ref<Map<string, any>[]>([])
let defaultPoint: any

let solution: Solution | null = null

let renderPending = false
let renderTimer: ReturnType<typeof setTimeout> | null = null

function resetRes() {
    allPoints.value = ([])
    solution = null
    defaultPoint = null
}

//function isModelType(type: string) {
//  const surrogate = experiment_description.value?.ConfigurationSelection?.Predictor?.Model.Surrogate?.Instance
//const surrogateType = surrogate ? Object.keys(surrogate)[0] : undefined
//return surrogateType === type
//console.log('isModelType:', type, result, experiment_description.value?.Predictor)
//return result
//}

const lastName = (s: string) => String(s).split('.').pop() ?? String(s)

//return an arry of values by key from all directionaries
function unpack(set: any, key: any) {
    let selection: any = []
    set.forEach((point: any) => {  // point is key value store - Map
        selection.push(point.get(key));
    });
    return selection
}
// merge key and values arrays in key
function zip(keys: Array<any>, values: Array<any>) {
    let result = new Map()
    if (keys.length == values.length) {
        keys.forEach((key, i) => result.set(key, values[i]))
    }
    return result
}
async function chose(configuration: any) {
    currentDiagram.value = experiment
    let index = rootParam.value.indexOf(currentDiagram.value)
    if (index === -1) {
        console.warn('Parameter not found:', currentDiagram.value, 'in', rootParam)
        return
    }
    parameter_names.value = Object.keys(searchspace.value["boundaries"][index]["Boundaries"])
    let rangeValues = Object.values(searchspace.value["boundaries"][index]["Boundaries"])
    const shortNames = parameter_names.value.map(lastName)
    resultParamsRange.value = zip(shortNames, rangeValues)
    resultParamsRange.value.set('result', undefined) // range for results is undefined

}

function initMainEvents() {

    watch([experiment_description, searchspace], () => {
        if (!experiment_description.value || !searchspace.value) {
            return
        }
        resetRes()

        rootParam.value = searchspace.value["root_parameters_list"]
        console.log('rootParam after:', rootParam.value)
        experiment = searchspace.value["name"]
        // ObjectPriorities does not exist on received data, updated new path 
        let priorities = experiment_description.value?.Context?.TaskConfiguration?.Objectives

        if (priorities) {
            keyParam.value = Object.keys(priorities)[0]  // → "energy"
        }

    },
        // reactive object from store, need deep to track properties of the object
        {
            deep: true,
            immediate: true
        })

    // Default configuration
    store.onEvent(MainEvent.DEFAULT)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            if (!rootParam.value || !experiment) {
                console.warn('not ready yet - rootParam or experiment not there ')
                return
            }
            let configs = JSON.parse(message.body)
            configs.forEach((configuration: any) => {
                if (configuration) {
                    chose(configuration)
                    if (!parameter_names.value) return
                    defaultPoint = configuration
                    let alphas = new Array();;
                    parameter_names.value.forEach((key: any) => {
                        alphas.push(configuration.configurations[key])
                    })
                    let point = zip(parameter_names.value.map(lastName), alphas)
                    point.set('result', configuration.results[keyParam.value])
                    allPoints.value.push(point)

                } else {
                    console.log("Empty default")
                }
            })
            console.log('Default:', configs)

            if (renderTimer) clearTimeout(renderTimer)
            renderTimer = setTimeout(() => {
                render()
                renderTimer = null
            }, 500)
        }
    });

    // New task results
    store.onEvent(MainEvent.NEW)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            if (!rootParam.value.length || !experiment) {
                return
            }
            let configs = JSON.parse(message.body)
            configs.forEach((configuration: any) => {
                if (configuration) {
                    chose(configuration)
                    if (!parameter_names.value) return
                    var alphas = new Array();;
                    parameter_names.value.forEach((key: any) => {
                        alphas.push(configuration.configurations[key])
                    })
                    let point = zip(parameter_names.value.map(lastName), alphas)
                    point.set('result', configuration.results[keyParam.value])
                    allPoints.value.push(point)

                }
                else {
                    console.log("Empty task")
                }
            })
            if (renderTimer) clearTimeout(renderTimer)
            renderTimer = setTimeout(() => {
                render()
                renderTimer = null
            }, 500)

        }
    });

    // The final configuration, suggested by BRISE.
    store.onEvent(MainEvent.FINAL)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            let configs = JSON.parse(message.body)
            configs.forEach((configuration: any) => {
                if (configuration) {
                    solution = configuration
                    console.log('Final:', configs)
                } else {
                    console.log("Empty solution")
                }
            })
        }
    });
}

function render() {

    const element = document.getElementById(currentDiagram.value)
    if (!element) {
        console.warn('element not found', currentDiagram.value)
        return
    }

    var trace = [{
        type: 'parcoords' as const,
        line: {
            showscale: true,
            // reversescale: true,
            colorscale: 'Jet',
            color: unpack(allPoints.value, 'result')
        },
        dimensions: dimmensionsData()
    }];

    var layout = {
        margin: {
            l: 150,

        },
        title: {
            text: currentDiagram.value,
            font: {
                size: 20
            },
            xref: 'paper' as const,
            x: 0.05,
        }
    }

    Plotly.react(element, trace, layout)
}

function factoryDimension(parameter: String, valuesRange: Array<any>) {
    let dimValues = unpack(allPoints.value, parameter)
    let dim: any = {
        values: dimValues,
        label: parameter.replace(/_/g, " ")
    }
    // If values are not numerical.
    if (valuesRange && (typeof valuesRange[0] == "string" || typeof valuesRange[0] == "boolean")) {
        dim.tickvals = Array.from(Array(valuesRange.length).keys())
        dim.ticktext = valuesRange
        dim.values = dimValues.map((value: any) => dim.tickvals[dim.ticktext.indexOf(value)])
    }
    return dim
}

function dimmensionsData() {
    let data: any = [] // accommodate dimensional obj
    resultParamsRange.value?.size && resultParamsRange.value.forEach((range: Array<any>, param: String) => {
        if (param != experiment) {
            let dim = factoryDimension(param, range) // make dimensional object through all results by one parameter
            data.push(dim) // add new dimension object for plotting
        }
    })
    return data
}

onMounted(() => {
    initMainEvents()
})

onUnmounted(() => {
    if (renderTimer) clearTimeout(renderTimer)
    const element = document.getElementById(currentDiagram.value)
    if (element) Plotly.purge(element)
})
</script>

<template>
    <div v-for="item in rootParam" :key="item">


        <div :id="item" style="width:100%; height:500px;"></div>

    </div>
</template>
