// front-end/src/app/components/charts/heat-map/heat-map.component.ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';

// Service
import {MainEventService} from '../../../core/services/main.event.service';

import { Event as SocketEvent } from '../../../data/client-enums';
import { MainEvent, SubEvent } from '../../../data/client-enums';
import { ExperimentDescription } from '../../../data/experimentDescription.model';

// Plot
import { PlotType as type } from '../../../data/client-enums';
import { Color as colors } from '../../../data/client-enums';
import { Smooth as smooth } from '../../../data/client-enums';
import { Solution } from '../../../data/taskData.model';

interface Configuration {
  configurations: Array<any>;
  results: any;
}

@Component({
  selector: 'hm',
  templateUrl: './heat-map.component.html',
  styleUrls: ['./heat-map.component.scss']
})
export class HeatMapComponent implements OnInit {

  // The experiments results
  result = new Map();

  // The prediction results from model
  prediction = new Map();

  globalConfig: object;
  experimentDescription: ExperimentDescription;
  searchspace: object;

  // Best point
  solution: Solution;
  configWithNones: String;
  // Measured points for the Regresion model from worker-service
  measPoints: Array<Array<any>> = [];
  defaultConfiguration: Configuration;

  // Rendering axises
  y: Array<any>;
  x: Array<any>;

  resetRes() {
    this.result.clear();
    this.prediction.clear();
    this.solution = undefined;
    this.measPoints = [];
    this.defaultConfiguration = undefined;
  }

  // Default theme
  theme = {
    type: type[0],
    color: colors[0],
    smooth: smooth[0]
  };

  // Values that possible to use
  public type = type;
  public colors = colors;
  public smooth = smooth;

  // poiner to DOM element #map
  @ViewChild('map') map: ElementRef;

  constructor(
    private ioMain: MainEventService,
  ) {
  }

  ngOnInit() {
    this.initMainEvents();
  }

  isModelType(type: String) {
    return this.experimentDescription && this.experimentDescription.ModelConfiguration.ModelType == type;
  }

  zParser(data: Map<String, any>): Array<Array<any>> {
    // Parse the answears in to array of Y rows
    const z = [];
    this.x &&
    this.y &&
    this.y.forEach(y => { // y - parameter2
      const row = [];
      this.x.forEach(x => { // x - parameter1
        const results = data.get(String([y, x])); // To get horizontal orientation - change to [x,y], vertical - [y,x]
        row.push(results && results[0]); // Get the first result from an array or mark it as undefined.

      });
      z.push(row);
    });
    return z;
  }

  render(): void {
    if (this.experimentDescription.ModelConfiguration.ModelType === 'regression') {
      const element = this.map.nativeElement;
      const data = [
        { // defined X and Y axises with data, type and color
          z: this.zParser(this.result),
          x: this.x.map(String),
          y: this.y.map(String),
          type: this.theme.type,
          colorscale: this.theme.color,
          zsmooth: this.theme.smooth
        },
        { // Measured points
          type: 'scatter',
          mode: 'markers',
          marker: { color: 'grey', size: 7, symbol: 'cross' },
          x: this.measPoints.map(arr => arr[1]),
          y: this.measPoints.map(arr => arr[0])
        },
        { // Best point. Solution
          type: 'scatter',
          mode: 'markers',
          hoverinfo: 'none',
          showlegend: false,
          marker: { color: 'Gold', size: 16, symbol: 'star' },
          x: this.solution && [this.solution.configurations[1]],
          y: this.solution && [this.solution.configurations[0]]
        }
      ];

      const layout = {
        title: 'Heat map results',
        autosize: true,
        showlegend: false,
        xaxis: {
          title: Object.keys(this.searchspace['boundaries'])[1],
          type: 'category',
          autorange: true,
          range: [Math.min(...this.x), Math.max(...this.x)],
          showgrid: true
        },
        yaxis: {
          title: Object.keys(this.searchspace['boundaries'])[0],
          type: 'category',
          autorange: true,
          range: [Math.min(...this.y), Math.max(...this.y)],
          showgrid: true
        }
      };

      Plotly.react(element, data, layout);
    }
  }
  // --------------------------   Main-node
  private initMainEvents(): void {
    //                            Main events

    this.ioMain.onEvent(MainEvent.EXPERIMENT)
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'description') {
          const obj = JSON.parse(message.body);
          this.resetRes();
          this.globalConfig = obj['global_configuration'];
          this.experimentDescription = obj['experiment_description'];
          this.searchspace = obj['searchspace_description'];
          let boundaryObj: Object;
          boundaryObj = this.searchspace['boundaries'];
          this.x = Object.values(boundaryObj)[1];
          this.y = Object.values(boundaryObj)[0];
        }
      });

    this.ioMain.onEvent(MainEvent.NEW) // New configuration results
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          const configs = JSON.parse(message.body);
          configs.forEach(configuration => {
            if (configuration) {
              this.result.set(String(configuration['configurations']), configuration['results']);
              this.measPoints.push(configuration['configurations']);
              console.log('New configuration:', configuration);
            } else {
              console.log('Empty configuration');
            }
          });
          this.render();
        }
      });
    this.ioMain.onEvent(MainEvent.FINAL) // The final configuration, suggested by BRISE.
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          const configs = JSON.parse(message.body);
          configs.forEach(configuration => {
            if (configuration) {
              this.solution = configuration; // In case if only one point solution
              this.configWithNones = String(this.solution.configurations);
              this.configWithNones = this.configWithNones.replace(',,', ',None,');
              console.log('Final:', configs);
            } else {
              console.log('Empty solution');
            }
          });
          this.render();
        }
      });
    this.ioMain.onEvent(MainEvent.DEFAULT) // Default configuration
      .subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
          const configs = JSON.parse(message.body);
          configs.forEach(configuration => {
            if (configuration) {
              this.defaultConfiguration = configuration; // In case if only one point default
              this.result.set(String(configuration['configurations']), configuration['results']);
              this.measPoints.push(configuration['configurations']);
            } else {
              console.log('Empty default');
            }
          });
          console.log('Default:', message.body);
          this.render();
        }
      });

  }

}

<mat-card>
  <h3>Experiment:</h3>
  <div class="button-row">
    <button mat-button (click)="startMain()" [disabled]="isRuning" color="primary">Start</button>
    <button mat-button (click)="stopMain()" [disabled]="!isRuning" color="warn">Stop</button>
    <mat-progress-bar mode="indeterminate" *ngIf=isRuning></mat-progress-bar>
  </div>

  <div class="heatmap">
    <div class="results">
      <div class="select-box" *ngIf=y&&x [hidden]='result'>
        <!-- select color -->
        <mat-form-field>
          <mat-select [(value)]="theme.color" (selectionChange)="render()" placeholder="Color">
            <mat-option *ngFor="let col of colors" [value]="col">
              {{col}}
            </mat-option>
          </mat-select>
        </mat-form-field>
        <!-- select type -->
        <mat-form-field>
          <mat-select [(value)]="theme.type" (selectionChange)="render()" placeholder="Type">
            <mat-option *ngFor="let t of type" [value]="t">
              {{t}}
            </mat-option>
          </mat-select>
        </mat-form-field>
        <!-- select smooth -->
        <mat-form-field>
          <mat-select [(value)]="theme.smooth" (selectionChange)="render()" placeholder="Smooth">
            <mat-option *ngFor="let s of smooth" [value]="s">
              {{s}}
            </mat-option>
          </mat-select>
        </mat-form-field>
      </div>
      <!-- ================  Heat map  ================ -->
      <div #map></div>
      <!-- ============================================ -->
    </div>
    
    <hm-reg class="regression"></hm-reg>
  </div>
  
  <!--         Solution         -->
  <mat-card *ngIf=solution class="chart-solution">
    <mat-icon matListIcon>star</mat-icon>
    <span>Solution: </span>
    <h3>{{solution.configuration}}</h3>
    <span>Result deviation: </span>
    <h3>{{(solution.result/default_task.result-1)*100 | number:'2.0-0'}}%</h3>
  </mat-card>
</mat-card>

// frontend-new/src/widgets/charts/heatmap/ui/Heatmap.vue
<script setup lang="ts">
import { ref, onMounted, watch, computed, nextTick } from 'vue'
import { storeToRefs } from 'pinia'

// Plotly
import Plotly from 'plotly.js-dist-min'
import { Color, PlotType, Smooth } from '../../model/chart.types'

import { MainEvent } from '../../../../entities/main'
import type { Solution } from '../../../../entities/task/model/task-data.model';

//service
import { useMainEventStore } from '../../../../entities/main'

interface Configuration {
    configurations: Array<any>;
    results: any;
}

// initialize store
const store = useMainEventStore()
// destructure reactive value from main.event.store
const { experiment_description, searchspace, globalConfig } = storeToRefs(store)

// experiment results
const result = ref(new Map<string, any>())

// prediction results from model
const prediction = ref(new Map<string, any>())

// best point
let solution: Solution
const configWithNones = ref('')
// Measured points for the Regresion model from worker-service
// is always an array of arrays (a tuple)
const measPoints = ref<Array<[any, any]>>([])
let defaultConfiguration: Configuration
let sol: any = ref()
let dc: any = ref()
let results = ref('')

// rendering axises
const x = ref<Array<any>>([])
const y = ref<Array<any>>([])


// default theme
const theme = ref({
    type: PlotType[0] as string,
    color: Color[0] as string,
    smooth: Smooth[0] as string | boolean
})

// values that possible to use in template
const colors = Color
const types = PlotType
const smoothOpt = Smooth

const map = ref<HTMLElement | null>(null)

function resetRes() {
    result.value?.clear()
    prediction.value?.clear()
    measPoints.value = []
}

const isModelType = computed(() => {
    const model = experiment_description.value?.ConfigurationSelection?.Predictor?.Model

    if (model?.Surrogate?.Instance?.LinearRegression) {
        return 'regression'
    }

    return 'unknown'
})

function zParser(data: Map<String, any>): Array<Array<any>> {
    // Parse the answears in to array of Y rows
    const z: any = []
    x.value &&
        y.value &&
        y.value.forEach((y: any) => { // y - parameter2
            const row: any = [];
            x.value.forEach((x: any) => { // x - parameter1
                const results = data.get(String([y, x])); // To get horizontal orientation - change to [x,y], vertical - [y,x]
                row.push(results && results[0]); // Get the first result from an array or mark it as undefined.

            });
            z.push(row);
        });
    return z;
}


function render(): void {

    // if (isModelType.value !== 'regression') return

    if (isModelType.value === 'regression') {
        const element = map.value
        const data: any[] = [
            { // defined X and Y axises with data, type and color
                z: zParser(result.value),
                x: x.value.map(String),
                y: y.value.map(String),
                type: theme.value.type,
                colorscale: theme.value.color,
                zsmooth: theme.value.smooth
            },
            { // Measured points
                type: 'scatter' as const,
                mode: 'markers' as const,
                marker: { color: 'grey', size: 7, symbol: 'cross' },
                x: measPoints.value.map(arr => arr[1]),
                y: measPoints.value.map(arr => arr[0])
            },
            { // Best point. Solution
                type: 'scatter' as const,
                mode: 'markers' as const,
                hoverinfo: 'none' as const,
                showlegend: false as const,
                marker: { color: 'Gold', size: 16, symbol: 'star' },
                x: solution && [solution.configurations[1]],
                y: solution && [solution.configurations[0]]
            }
        ];

        const layout: any = {
            margin: { l: 220 },
            title: { text: 'Heat map results' } as any,
            autosize: true,
            showlegend: false,
            xaxis: {
                title: Object.keys(searchspace.value.boundaries[0].Boundaries)[1],
                type: 'category' as const,
                autorange: true,
                range: [-0.5, x.value.length - 0.5],
                showgrid: true,
                categoryorder: 'array',
                categoryarray: x.value
            },
            yaxis: {
                title: Object.keys(searchspace.value.boundaries[0].Boundaries)[0],
                type: 'category' as const,
                autorange: true,
                range: [-0.5, y.value.length - 0.5],
                showgrid: true,
                categoryorder: 'array',
                categoryarray: y.value
            }
        };
        if (element)
            Plotly.react(element, data, layout);
    }
}

const lastName = (s: string) => String(s).split('.').pop() ?? String(s)
function initMainEvents() {
    watch(experiment_description, () => {
        if (!experiment_description.value || !searchspace.value || !globalConfig.value) {
            return
        }
        // Log the model type for debugging
        console.log('model types: ', experiment_description.value?.ConfigurationSelection?.Predictor?.Model)

        resetRes()

        const boundaryObj = searchspace.value?.boundaries?.[0]?.Boundaries
        x.value = (boundaryObj?.threads ?? []).map(lastName)
        y.value = (boundaryObj?.frequency ?? []).map(lastName)
        console.log('x FIXED:', x.value)
        console.log('y FIXED:', y.value)
    }, { deep: true })

    // new configuration results
    store.onEvent(MainEvent.NEW)?.subscribe((message: any) => {
        const configs = JSON.parse(message.body)
        configs.forEach((configuration: any) => {
            if (configuration) {
                const conf = configuration['configurations'];
                const freq = lastName(conf.frequency);
                const threads = lastName(conf.threads);
                result.value.set(String([freq, threads]), configuration['results']);
                measPoints.value.push([freq, threads]);
                console.log('New configuration:', configuration);
            } else {
                console.log('Empty configuration');
            }
        });
        nextTick(() => render())
    })

    // The final configuration, suggested by BRISE.

    store.onEvent(MainEvent.FINAL)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            const configs = JSON.parse(message.body);
            configs.forEach((configuration: any) => {
                if (configuration) {
                    solution = configuration; // In case if only one point solution
                    defaultConfiguration = configuration;
                    configWithNones.value = JSON.stringify(solution.configurations, null, '\t');
                    configWithNones.value = configWithNones.value.replace(',,', ',None,');
                    results.value = JSON.stringify(solution.results)
                    const conf = configuration['configurations'];
                    result.value.set(String([lastName(conf.frequency), lastName(conf.threads)]), configuration['results']);
                    measPoints.value.push([lastName(conf.frequency), lastName(conf.threads)]);
                    sol = Object.values(solution.results)
                    dc = Object.values(defaultConfiguration.results)
                    console.log('Final:', configs);
                } else {
                    console.log('Empty solution');
                }
            });
            render();
        }
    });

    // Default configuration
    store.onEvent(MainEvent.DEFAULT)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            const configs = JSON.parse(message.body);
            configs.forEach((configuration: any) => {
                if (configuration) {
                    defaultConfiguration = configuration; // In case if only one point default
                    result.value.set(String(configuration['configurations']), configuration['results']);
                    measPoints.value.push(configuration['configurations']);
                } else {
                    console.log('Empty default');
                }
            });
            console.log('Default:', message.body);
            render();
        }
    });

}

onMounted(() => {
    initMainEvents()
})


</script>
<template>

    <div v-if="isModelType === 'regression'">
        <div ref="map"></div>
    </div>
    <select v-model="theme.color" @change="render">
        <option v-for="col in colors" :key="col" :value="col">
            {{ col }}
        </option>
    </select>
    <select v-model="theme.type" @change="render">
        <option v-for="type in types" :key="type" :value="type">
            {{ type }}
        </option>
    </select>

</template>
