// front-end/src/app/components/charts/imp-res/imp-res.component.ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';

// Service
import { MainSocketService } from '../../../core/services/main.socket.service';

import { Solution } from '../../../data/taskData.model';
import { MainEvent } from '../../../data/client-enums';

import { TaskConfig } from '../../../data/taskConfig.model';

interface PointExp {
  configurations: Array<any>;
  results: Array<any>;
  time: any;
  'measured points': number;
} 

@Component({
  selector: 'imp-res',
  templateUrl: './imp-res.component.html',
  styleUrls: ['./imp-res.component.scss']
})
export class ImpResComponent implements OnInit {
  // The experements results
  bestRes = new Set<PointExp>()
  allRes = new Set<PointExp>()
  // Best point 
  solution: Solution

  taskConfig: TaskConfig

  // poiner to DOM element #map
  @ViewChild('improvement') impr: ElementRef;

  constructor(private ioMain: MainSocketService) { }

  ngOnInit() {
    this.initMainEvents();
    window.onresize = () => this.bestRes.size>2 && this.render()
  }
  //                              WebSocket
  // --------------------------   Main-node
  private initMainEvents(): void {
    this.ioMain.onEvent(MainEvent.EXPERIMENT)
      .subscribe((obj: any) => {
        this.taskConfig = obj['configuration']['experiment configuration']
      });

    this.ioMain.onEvent(MainEvent.FINAL)
      .subscribe((obj: any) => {
        obj["task"] && obj["task"].forEach(task => {
          this.solution = task
          let min = new Date().getMinutes()
          let sec = new Date().getSeconds()
          let temp: PointExp = {
            'configurations': task['configurations'],
            'results': task['results'],
            'time': min + 'm ' + sec + 's',
            'measured points': task['measured points']
          }
          this.allRes.add(temp)
          this.bestRes.add(temp) // There is no check if this solution is the best decision 
        })
        this.render() // Render chart when all points got
      });


    this.ioMain.onEvent(MainEvent.NEW)
      .subscribe((obj: any) => {
        obj["task"] && obj["task"].forEach(task => {
          let min = new Date().getMinutes()
          let sec = new Date().getSeconds()
          this.allRes.add({
            'configurations': task['configurations'],
            'results': task['results'],
            'time': min + 'm ' + sec + 's',
            'measured points': this.allRes.size + 1
          }) // Add new point(result)
          let temp: PointExp = {
            'configurations': task['configurations'],
            'results': task['results'],
            'time': min + 'm ' + sec + 's',
            'measured points': this.allRes.size
          }

          // Check the best available point
          this.bestRes && this.bestRes.forEach(function (resItem) {
            // TODO: Max or min from task
            if (temp.results[0] > resItem.results[0]) { // check FIRST result from array!
              temp.results = resItem.results
              temp.configurations = resItem.configurations
            }
          })
          this.bestRes.add(temp) // Add the best available point(result)
        })
        this.render() // Render chart
        this.bestRes.size>2 && this.render()
      });

    this.ioMain.onEvent(MainEvent.EXPERIMENT)
      .subscribe((obj: any) => {
        if (obj["configuration"]) {
          this.bestRes.clear()
          this.allRes.clear()
          this.solution = undefined
        }
      });
  }

  render() {
    // DOM element. Render point
    const element = this.impr.nativeElement

    // X-axis data
    const xBest = Array.from(this.bestRes).map(i => i["measured points"]);
    // Results
    const yBest = Array.from(this.bestRes).map(i => i["results"][0]);
    
    var allResultSet = { // Data for all results
      x: Array.from(this.allRes).map(i => i["measured points"]),
      y: Array.from(this.allRes).map(i => i["results"][0]),
      type: 'scatter',
      mode: 'lines+markers',
      line: { color: 'rgba(67,67,67,1)', width: 1, shape: 'spline', dash: 'dot' },
      text: Array.from(this.allRes).map(i => String(i["configurations"])),
      marker: {
        color: 'rgba(255,64,129,1)',
        size: 8,
        symbol: 'x'
      },
      name: 'results'
    }
    var bestPointSet = { // Data for the best available results 
      x: xBest,
      y: yBest,
      type: 'scatter',
      mode: 'lines+markers',
      line: { color: 'rgba(67,67,67,1)', width: 2, shape: 'spline' },
      name: 'best point',
      marker: { size: 6, symbol: 'x', color: 'rgba(67,67,67,1)' }
    }

    var startEndPoint = { // Start & Finish markers
      x: [xBest[0], xBest[xBest.length - 1]],
      y: [yBest[0], yBest[yBest.length - 1]],
      type: 'scatter',
      mode: 'markers',
      hoverinfo: 'none',
      showlegend: false,
      marker: { color: 'rgba(255,64,129,1)', size: 10 }
    }

    let data = [allResultSet, bestPointSet, startEndPoint];

    var layout = {
      title: 'The best results',
      showlegend: true,
      autosize: true,
      xaxis: {
        title: "Sequence number",
        showline: true,
        showgrid: false,
        zeroline: false,
        showticklabels: true,
        linecolor: 'rgb(204,204,204)',
        linewidth: 2,
        autotick: false,
        ticks: 'outside',
        tickcolor: 'rgb(204,204,204)',
        tickwidth: 2,
        ticklen: 5,
        tickfont: {
          family: 'Roboto',
          size: 12,
          color: 'rgb(82, 82, 82)'
        }
      },
      yaxis: {
        title: "Energy",
        showgrid: false,
        zeroline: false,
        showline: true,
        linecolor: 'rgb(204,204,204)',
        showticklabels: true,
        ticks: 'outside',
        tickcolor: 'rgb(204,204,204)',
        ticklen: 5,
        tickfont: {
          family: 'Roboto',
          size: 12,
          color: 'rgb(82, 82, 82)'
        }
      },
    };

    Plotly.react(element, data, layout);
  }

}
<div #improvement>
    
</div>

// frontend-new/src/widgets/charts/imp-res/ui/ImpRes.vue
<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'
import { storeToRefs } from 'pinia'

// Plotly
import Plotly from 'plotly.js-dist-min'

import { MainEvent } from '../../../../entities/main'
import type { Solution } from '../../../../entities/task/model/task-data.model';

//service
import { useMainEventStore } from '../../../../entities/main'

interface PointExp {
    configurations: Array<any>;
    results: Array<any>;
    time: any;
    'measured points': number;
}
// initialize store
const store = useMainEventStore()
// destructure reactive value from main.event.store
const { experiment_description } = storeToRefs(store)

let solution: Solution

const isVisible = ref(false)

//best point 
const bestRes = ref<PointExp[]>([])
// experiment results
const allRes = ref<PointExp[]>([])

const impr = ref<HTMLElement | null>(null)

onMounted(() => {
    initMainEvents()
})

function initMainEvents() {
    watch(experiment_description, () => {
        bestRes.value = []
        allRes.value = []
        // pointer to dom element 
        const element = impr.value
        isVisible.value = false
        if (element)
            Plotly.purge(element)
    })

    // add start point
    store.onEvent(MainEvent.DEFAULT)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            const configs = JSON.parse(message.body)
            configs.forEach((configuration: any) => {
                solution = configuration
                const min = new Date().getMinutes();
                const sec = new Date().getSeconds();
                const temp: any = {
                    'configurations': Object.values(configuration.configurations),
                    'results': Object.values(configuration.results),
                    'time': min + 'm ' + sec + 's',
                    'measured points': allRes.value.length + 1
                };
                allRes.value.push(temp)
                bestRes.value.push(temp)
            })
            render() // render chart when all points got
        }
    })

    // add last point
    store.onEvent(MainEvent.FINAL)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            const configs = JSON.parse(message.body);
            configs.forEach((configuration: any) => {
                solution = configuration;
                const min = new Date().getMinutes();
                const sec = new Date().getSeconds();
                const temp: any = {
                    'configurations': Object.values(configuration.configurations),
                    'results': Object.values(configuration.results),
                    'time': min + 'm ' + sec + 's',
                    'measured points': allRes.value.length + 1
                };
                allRes.value.push(temp);
                bestRes.value.push(temp); // There is no check if this solution is the best decision
            });
        }
        render(); // Render chart when all points got
    })

    // add new point
    store.onEvent(MainEvent.NEW)?.subscribe((message: any) => {
        if (message.headers['message_subtype'] === 'configuration') {
            const configs = JSON.parse(message.body);
            configs.forEach((configuration: any) => {
                const min = new Date().getMinutes();
                const sec = new Date().getSeconds();
                allRes.value.push({
                    'configurations': Object.values(configuration.configurations),
                    'results': Object.values(configuration.results),
                    'time': min + 'm ' + sec + 's',
                    'measured points': allRes.value.length + 1
                }) // add new point (resut)

                const temp: PointExp = {
                    'configurations': Object.values(configuration.configurations),
                    'results': Object.values(configuration.results),
                    'time': min + 'm ' + sec + 's',
                    'measured points': allRes.value.length
                }

                // check the best availbale point
                const descr = experiment_description.value
                bestRes.value && bestRes.value.forEach(function (resItem) {
                    let objectives = descr?.['Context']?.['TaskConfiguration']?.['Objectives'] as any
                    if (!objectives) return
                    const firstObjectiveKey = Object.keys(objectives)[0]
                    console.log('TaskConfig', descr?.['TaskConfiguration'])
                    const isMinimization = objectives?.[firstObjectiveKey]?.['Minimization']
                    if (isMinimization === true) {
                        if (temp.results[0] > resItem.results[0]) { // check FIRST result from array!
                            temp.results = resItem.results;
                            temp.configurations = resItem.configurations;
                        } else {
                            if (temp.results[0] < resItem.results[0]) { // check FIRST result from array!
                                temp.results = resItem.results;
                                temp.configurations = resItem.configurations;
                            }
                        }

                    }
                    bestRes.value.push(temp) // add the best availbale point(result)      

                })
                bestRes.value.length > 2 && render()
            })
        }

    })
}



function render() {
    // DOM element. Render point

    const element = impr.value

    isVisible.value = true
    // X-axis data
    const xBest = Array.from(bestRes.value).map((i: any) => i['measured points']);
    // Results
    const yBest = Array.from(bestRes.value).map((i: any) => i['results'][0]);

    const allResultSet = { // Data for all results
        x: Array.from(allRes.value).map((i: any) => i['measured points']),
        y: Array.from(allRes.value).map((i: any) => i['results'][0]),
        type: 'scatter' as const,
        mode: 'lines+markers' as const,
        line: { color: 'rgba(67,67,67,1)', width: 1, shape: 'spline' as const, dash: 'dot' as const },
        text: Array.from(allRes.value).map((i: any) => String(i['configurations'])),
        marker: {
            color: 'rgba(255,64,129,1)',
            size: 8,
            symbol: 'x' as const
        },
        name: 'results'
    };
    const bestPointSet = { // Data for the best available results
        x: xBest,
        y: yBest,
        type: 'scatter' as const,
        mode: 'lines+markers' as const,
        line: { color: 'rgba(67,67,67,1)', width: 2, shape: 'spline' as const },
        name: 'best point',
        marker: { size: 6, symbol: 'x' as const, color: 'rgba(67,67,67,1)' }
    };

    const startEndPoint = { // Start & Finish markers
        x: [xBest[0], xBest[xBest.length - 1]],
        y: [yBest[0], yBest[yBest.length - 1]],
        type: 'scatter' as const,
        mode: 'markers' as const,
        hoverinfo: 'none' as const,
        showlegend: false,
        marker: { color: 'rgba(255,64,129,1)', size: 10 }
    };

    const data = [allResultSet, bestPointSet, startEndPoint];

    const layout = {
        title: { text: 'The best results' } as const,
        showlegend: true,
        autosize: true,
        xaxis: {
            title: { text: 'Sequence number' } as const,
            showline: true,
            showgrid: false,
            zeroline: false,
            showticklabels: true,
            linecolor: 'rgb(204,204,204)',
            linewidth: 2,
            autotick: false,
            ticks: 'outside' as const,
            tickcolor: 'rgb(204,204,204)',
            tickwidth: 2,
            ticklen: 5,
            tickfont: {
                family: 'Roboto',
                size: 12,
                color: 'rgb(82, 82, 82)'
            }
        },
        yaxis: {
            title: { text: experiment_description.value?.['TaskConfiguration']?.['Objectives'][0] } as const,
            showgrid: false,
            zeroline: false,
            showline: true,
            linecolor: 'rgb(204,204,204)',
            showticklabels: true,
            ticks: 'outside' as const,
            tickcolor: 'rgb(204,204,204)',
            ticklen: 5,
            tickfont: {
                family: 'Roboto',
                size: 12,
                color: 'rgb(82, 82, 82)'
            }
        },
    };
    if (element)
        Plotly.react(element, data, layout);
}

</script>

<template>
    <div v-show="isVisible" ref="impr"></div>
</template>
